# Savage War Beast and War Chief Rehkta - Legacy of the Rakata
# Auto-converted from Orbs timers

[[boss]]
id = "savage_war_beast_and_war_chief_rehkta"
name = "Savage War Beast and War Chief Rehkta"
area_name = "Legacy of the Rakata"
difficulties = ["master", "veteran"]
npc_names = ["Savage War Beast and War Chief Rehkta"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "savage_war_beast_and_war_chief_rehkta_swipe"
name = "Swipe"
trigger = { type = "ability_cast", ability_ids = [3375986028576768] }
duration_secs = 8.0
color = [220, 114, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "savage_war_beast_and_war_chief_rehkta_slam"
name = "Slam"
trigger = { type = "ability_cast", ability_ids = [3378090562551808] }
duration_secs = 30.0
color = [32, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "savage_war_beast_and_war_chief_rehkta_ignite"
name = "Ignite"
trigger = { type = "ability_cast", ability_ids = [3376535784390656] }
duration_secs = 10.0
color = [213, 28, 25, 255]
difficulties = ["veteran", "master"]
