# Kyramla Gemas'rugam - Blood Hunt
# Auto-converted from Orbs timers

[[boss]]
id = "kyramla_gemas_rugam"
name = "Kyramla Gemas'rugam"
area_name = "Blood Hunt"
difficulties = ["master", "veteran"]
npc_names = ["Kyramla Gemas'rugam"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "kyramla_gemas_rugam_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 255.0
color = [220, 40, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_swipe"
name = "Swipe"
trigger = { type = "ability_cast", ability_ids = [3528062230593536] }
duration_secs = 25.0
color = [228, 121, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_smash_1st"
name = "Smash 1st"
trigger = { type = "combat_start" }
duration_secs = 27.0
color = [27, 223, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_swipe_adds"
name = "Swipe + Adds"
trigger = { type = "combat_start" }
duration_secs = 17.0
color = [228, 118, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3390988349341696] }
duration_secs = 29.0
color = [27, 151, 43, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_smash_ends"
name = "Smash Ends"
trigger = { type = "ability_cast", ability_ids = [3528066525560832] }
duration_secs = 9.0
color = [32, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kyramla_gemas_rugam_smash"
name = "Smash"
trigger = { type = "timer_expires", timer_id = "kyramla_gemas_rugam_smash_ends" }
duration_secs = 19.5
color = [32, 220, 210, 255]
difficulties = ["veteran", "master"]
