# Valk & Jos - Blood Hunt
# Auto-converted from Orbs timers

[[boss]]
id = "valk_jos"
name = "Valk & Jos"
area_name = "Blood Hunt"
difficulties = ["master", "veteran"]
npc_names = ["Valk & Jos"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "valk_jos_jet_charge"
name = "Jet Charge"
trigger = { type = "ability_cast", ability_ids = [3395794417745920] }
duration_secs = 30.0
color = [228, 122, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valk_jos_aerial_strike"
name = "Aerial Strike"
trigger = { type = "ability_cast", ability_ids = [3394445798014976] }
duration_secs = 33.0
color = [220, 36, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valk_jos_missiles"
name = "Missiles"
trigger = { type = "ability_cast", ability_ids = [3395824482516992] }
duration_secs = 10.5
color = [213, 203, 25, 255]
difficulties = ["veteran", "master"]
