# General Ortol - Cademimu
# Auto-converted from Orbs timers

[[boss]]
id = "general_ortol"
name = "General Ortol"
area_name = "Cademimu"
difficulties = ["master", "veteran"]
npc_names = ["General Ortol"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "general_ortol_root"
name = "Root"
trigger = { type = "ability_cast", ability_ids = [2506624518324224] }
duration_secs = 15.0
color = [39, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "general_ortol_knocback"
name = "Knocback"
trigger = { type = "ability_cast", ability_ids = [2694782740594688] }
duration_secs = 15.0
color = [220, 122, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "general_ortol_single_rocket"
name = "Single Rocket"
trigger = { type = "ability_cast", ability_ids = [3213541775507456] }
duration_secs = 30.0
color = [208, 220, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "general_ortol_multi_rocket"
name = "Multi Rocket"
trigger = { type = "ability_cast", ability_ids = [3213546070474752] }
duration_secs = 30.0
color = [213, 194, 31, 255]
difficulties = ["veteran", "master"]
