# Officer Xander - Cademimu
# Auto-converted from Orbs timers

[[boss]]
id = "officer_xander"
name = "Officer Xander"
area_name = "Cademimu"
difficulties = ["master", "veteran"]
npc_names = ["Officer Xander"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "officer_xander_droid_activation"
name = "Droid Activation_"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [9, 151, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "officer_xander_droid_activation_2"
name = "Droid Activation"
trigger = { type = "ability_cast", ability_ids = [3230876263514112] }
duration_secs = 45.0
color = [22, 151, 36, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "officer_xander_sticky_grenade"
name = "Sticky Grenade"
trigger = { type = "ability_cast", ability_ids = [3232955027685376] }
duration_secs = 15.0
color = [182, 180, 16, 255]
difficulties = ["veteran", "master"]
