# Red - Dxun
# Auto-converted from Orbs timers

[[boss]]
id = "red"
name = "Red"
area_name = "Dxun"
difficulties = ["master", "veteran"]
npc_names = ["Red"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "red_bull_1st"
name = "Bull 1st"
trigger = { type = "combat_start" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_bull_2nd"
name = "Bull 2nd"
trigger = { type = "timer_expires", timer_id = "red_bull_1st" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_bull_3rd"
name = "Bull 3rd"
trigger = { type = "timer_expires", timer_id = "red_bull_2nd" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_bull_4th"
name = "Bull 4th"
trigger = { type = "timer_expires", timer_id = "red_bull_3rd" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_bull_5th"
name = "Bull 5th"
trigger = { type = "timer_expires", timer_id = "red_bull_4th" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_bull_6th"
name = "Bull 6th"
trigger = { type = "timer_expires", timer_id = "red_bull_5th" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_bull_7th"
name = "Bull 7th"
trigger = { type = "timer_expires", timer_id = "red_bull_6th" }
duration_secs = 60.0
color = [219, 93, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_enrage_bull"
name = "Enrage + Bull"
trigger = { type = "timer_expires", timer_id = "red_bull_7th" }
duration_secs = 60.0
color = [219, 28, 180, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_hydrochloric_pool_1st"
name = "Hydrochloric Pool 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [23, 123, 8, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_hydrochloric_pool"
name = "Hydrochloric Pool"
trigger = { type = "ability_cast", ability_ids = [4250097772658688] }
duration_secs = 47.0
color = [23, 123, 8, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_acidic_jet_1st"
name = "Acidic Jet 1st"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [224, 25, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "red_acidic_jet"
name = "Acidic Jet"
trigger = { type = "ability_cast", ability_ids = [4250089182724096] }
duration_secs = 30.0
color = [224, 25, 24, 255]
difficulties = ["veteran", "master"]
