# Sparky - The Ravagers
# Auto-converted from Orbs timers

[[boss]]
id = "sparky"
name = "Sparky"
area_name = "The Ravagers"
difficulties = ["master", "veteran"]
npc_names = ["Sparky"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "sparky_shoulder_throw"
name = "Shoulder Throw"
trigger = { type = "ability_cast", ability_ids = [3377850044383232] }
duration_secs = 13.0
color = [203, 204, 46, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_rampage_end"
name = "Rampage END"
trigger = { type = "ability_cast", ability_ids = [3380452794564608] }
duration_secs = 15.0
color = [187, 29, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_rampage_p2"
name = "Rampage P2"
trigger = { type = "timer_expires", timer_id = "sparky_rampage_end" }
duration_secs = 36.0
color = [187, 29, 224, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_body_slam"
name = "Body Slam_"
trigger = { type = "ability_cast", ability_ids = [3377991778304000] }
duration_secs = 13.0
color = [224, 29, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_body_slam_2"
name = "Body Slam"
trigger = { type = "ability_cast", ability_ids = [3377850044383232] }
duration_secs = 25.0
color = [219, 34, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_rampage_p3"
name = "Rampage P3"
trigger = { type = "timer_expires", timer_id = "sparky_rampage_end" }
duration_secs = 46.0
color = [187, 29, 224, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_forceful_roar_adds"
name = "Forceful Roar (Adds)"
trigger = { type = "ability_cast", ability_ids = [3380792096980992] }
duration_secs = 40.5
color = [34, 173, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_roar_adds"
name = "Roar (Adds)"
trigger = { type = "ability_cast", ability_ids = [3378502879412224] }
duration_secs = 17.5
color = [34, 173, 19, 255]
difficulties = ["veteran", "master"]
