# Karagga's Palace
# 4 boss(es)

[area]
name = "Karagga's Palace"
area_id = 833571547775669

# ─── bonethrasher ───
[[boss]]
id = "bonethrasher"
name = "Bonethrasher"
difficulties = ["master", "veteran"]
npc_names = ["Bonethrasher"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "bonethrasher_super_smash_1st"
name = "Super Smash 1st"
trigger = { type = "timer_expires", timer_id = "81d3ba6b-e952-4273-b0ff-28e1d0d949e9" }
duration_secs = 10.0
color = [39, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bonethrasher_smash_1st"
name = "Smash 1st"
trigger = { type = "timer_expires", timer_id = "bonethrasher_super_smash_1st" }
duration_secs = 10.0
color = [220, 26, 180, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bonethrasher_sweep_cs"
name = "Sweep CS"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [224, 103, 29, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_super_smash_cs"
name = "Super Smash CS"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [29, 224, 221, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_smash_cs"
name = "Smash CS"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [224, 24, 212, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_about_to_eat"
name = "About to Eat"
trigger = { type = "timer_expires", timer_id = "bonethrasher_gammorean" }
duration_secs = 10.0
color = [190, 178, 34, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_gammorean"
name = "Gammorean"
trigger = { type = "ability_cast", ability_ids = [2068658113216512] }
duration_secs = 10.0
color = [190, 178, 34, 255]
difficulties = ["veteran"]

# ─── foreman_crusher ───
[[boss]]
id = "foreman_crusher"
name = "Foreman Crusher"
difficulties = ["veteran"]
npc_names = ["Foreman Crusher"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "foreman_crusher_frenzy_1st"
name = "Frenzy 1st"
trigger = { type = "combat_start" }
duration_secs = 45.0
color = [224, 33, 181, 255]
difficulties = ["veteran"]

# ─── jarg_sorno ───
[[boss]]
id = "jarg_sorno"
name = "Jarg & Sorno"
difficulties = ["veteran"]
npc_names = ["Jarg & Sorno"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "jarg_sorno_sorno_back"
name = "Sorno back"
trigger = { type = "ability_cast", ability_ids = [2759280264478720] }
duration_secs = 30.0
color = [219, 24, 24, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "jarg_sorno_thermal_detonator"
name = "Thermal Detonator_"
trigger = { type = "ability_cast", ability_ids = [2759284559446016] }
duration_secs = 16.0
color = [224, 33, 35, 255]
difficulties = ["veteran"]

# ─── karagga_the_unyielding ───
[[boss]]
id = "karagga_the_unyielding"
name = "Karagga the Unyielding"
difficulties = ["veteran"]
npc_names = ["Karagga the Unyielding"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "karagga_the_unyielding_cluster_bombs_1st"
name = "Cluster Bombs 1st"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [204, 195, 46, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_unstable_energy_1st"
name = "Unstable Energy 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [186, 29, 224, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_burning_oil_1st"
name = "Burning Oil 1st"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [123, 86, 42, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_tunneling_drill_1st"
name = "Tunneling Drill 1st"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [224, 29, 29, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_mouse_droids"
name = "Mouse Droids"
trigger = { type = "ability_cast", ability_ids = [2778268314894336] }
duration_secs = 60.0
color = [61, 143, 61, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_mouse_droids_1st"
name = "Mouse Droids 1st"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [61, 143, 61, 255]
difficulties = ["veteran"]
