# Terror From Beyond
# 5 boss(es)

[area]
name = "Terror From Beyond"
area_id = 137438992720

# ─── kephess_the_undying ───
[[boss]]
id = "kephess_the_undying"
name = "Kephess the Undying"
difficulties = ["master", "veteran"]
npc_names = ["Kephess the Undying"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "kephess_the_undying_invulnerable"
name = "Invulnerable"
trigger = { type = "ability_cast", ability_ids = [3008070540066816] }
duration_secs = 9.0
color = [20, 154, 174, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_laser_blast"
name = "Laser Blast"
trigger = { type = "ability_cast", ability_ids = [3012687629910016] }
duration_secs = 4.5
color = [46, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_corrupted_nanites"
name = "Corrupted Nanites"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [49, 190, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_corrupted_nanites_2"
name = "Corrupted Nanites_"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [39, 197, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "kephess_the_undying_nanites_jump"
name = "Nanites + Jump_"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [220, 45, 32, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "kephess_the_undying_nanites_jump_2"
name = "Nanites + Jump"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [220, 36, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_1st_nanites_jump"
name = "1st Nanites + Jump"
trigger = { type = "ability_cast", ability_ids = [3008070540066816] }
duration_secs = 15.0
color = [222, 31, 30, 255]
difficulties = ["veteran", "master"]

# ─── operator_ix ───
[[boss]]
id = "operator_ix"
name = "Operator IX"
difficulties = ["master", "veteran"]
npc_names = ["Operator IX"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "operator_ix_black_obtuse"
name = "Black Obtuse"
trigger = { type = "ability_cast", ability_ids = [2998471288160256] }
duration_secs = 30.0
color = [227, 112, 31, 255]
difficulties = ["veteran", "master"]

# ─── the_dread_guard ───
[[boss]]
id = "the_dread_guard"
name = "The Dread Guard"
difficulties = ["master", "story", "veteran"]
npc_names = ["The Dread Guard"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_dread_guard_doom"
name = "Doom"
trigger = { type = "effect_applied", effect_ids = [3014573120552960] }
duration_secs = 34.0
color = [227, 27, 28, 255]
difficulties = ["master"]

[[boss.timer]]
id = "the_dread_guard_doom_vet"
name = "Doom Vet"
trigger = { type = "effect_applied", effect_ids = [3014573120552960] }
duration_secs = 24.0
color = [227, 27, 28, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "the_dread_guard_choke_1st"
name = "Choke 1st"
trigger = { type = "effect_removed", effect_ids = [2997483445682176] }
duration_secs = 15.0
color = [20, 131, 18, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_dread_guard_choke"
name = "Choke"
trigger = { type = "ability_cast", ability_ids = [3014616070225920] }
duration_secs = 30.0
color = [19, 126, 15, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_dread_guard_empowered_barrier_1st_mm"
name = "Empowered Barrier 1st MM"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [26, 26, 225, 255]
difficulties = ["master"]

[[boss.timer]]
id = "the_dread_guard_lightning_1st_mm"
name = "Lightning 1st MM"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [28, 177, 195, 255]
difficulties = ["master"]

[[boss.timer]]
id = "the_dread_guard_empowered_barrier_1st"
name = "Empowered Barrier 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [26, 26, 225, 255]
difficulties = ["story", "veteran"]

[[boss.timer]]
id = "the_dread_guard_lightning_1st"
name = "Lightning 1st"
trigger = { type = "combat_start" }
duration_secs = 45.0
color = [28, 177, 195, 255]
difficulties = ["story", "veteran"]

[[boss.timer]]
id = "the_dread_guard_empowered_barrier_vm"
name = "Empowered Barrier VM"
trigger = { type = "ability_cast", ability_ids = [2988107532075008] }
duration_secs = 55.0
color = [40, 30, 222, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "the_dread_guard_lightning_copy"
name = "Lightning (COPY)"
trigger = { type = "ability_cast", ability_ids = [2988369525080064] }
duration_secs = 55.0
color = [26, 174, 188, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "the_dread_guard_empowered_barrier"
name = "Empowered Barrier"
trigger = { type = "ability_cast", ability_ids = [2988107532075008] }
duration_secs = 45.0
color = [40, 30, 222, 255]
difficulties = ["master"]

[[boss.timer]]
id = "the_dread_guard_lightning"
name = "Lightning"
trigger = { type = "ability_cast", ability_ids = [2988369525080064] }
duration_secs = 45.0
color = [26, 174, 188, 255]
difficulties = ["master"]

[[boss.timer]]
id = "the_dread_guard_force_leech_1st"
name = "Force Leech 1st"
trigger = { type = "effect_applied", effect_ids = [836045448945500] }
duration_secs = 7.0
color = [134, 30, 222, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_dread_guard_overload"
name = "Overload"
trigger = { type = "ability_cast", ability_ids = [3014530170880000] }
duration_secs = 19.0
color = [222, 117, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_dread_guard_force_leech"
name = "Force Leech"
trigger = { type = "ability_cast", ability_ids = [3007065517719552] }
duration_secs = 14.0
color = [128, 30, 222, 255]
difficulties = ["veteran", "master"]

# ─── the_terror_from_beyond ───
[[boss]]
id = "the_terror_from_beyond"
name = "The Terror From Beyond"
difficulties = ["master", "veteran"]
npc_names = ["The Terror From Beyond"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_terror_from_beyond_grasping_slam"
name = "Grasping Slam"
trigger = { type = "ability_cast", ability_ids = [3025877474476032] }
duration_secs = 19.0
color = [229, 26, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_spit_pool_scream"
name = "Spit Pool + Scream"
trigger = { type = "effect_applied", effect_ids = [3052914293604611] }
duration_secs = 28.0
color = [228, 127, 40, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_spit_pool_scream_2"
name = "Spit Pool + Scream_"
trigger = { type = "timer_expires", timer_id = "eb2d7ff9-f2e3-423f-9c85-9adb2dbd66e9" }
duration_secs = 25.0
color = [220, 121, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_tunneling_slam_1st"
name = "Tunneling Slam 1st"
trigger = { type = "combat_start" }
duration_secs = 19.0
color = [213, 45, 38, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_beacon"
name = "Beacon_"
trigger = { type = "timer_expires", timer_id = "the_terror_from_beyond_void_disturbance" }
duration_secs = 4.0
color = [40, 64, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_adds"
name = "Adds_"
trigger = { type = "timer_expires", timer_id = "the_terror_from_beyond_beacon" }
duration_secs = 5.0
color = [20, 136, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_tunneling_slam"
name = "Tunneling Slam_"
trigger = { type = "timer_expires", timer_id = "55fdb26c-6305-4b0c-8803-84beb019fe9c" }
duration_secs = 15.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_void_disturbance"
name = "Void Disturbance_"
trigger = { type = "timer_expires", timer_id = "the_terror_from_beyond_tunneling_slam_1st" }
duration_secs = 7.0
color = [31, 209, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_adds_2"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3025903244279808] }
duration_secs = 30.0
color = [20, 136, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_void_disturbance_2"
name = "Void Disturbance"
trigger = { type = "timer_expires", timer_id = "the_terror_from_beyond_void_disturbance" }
duration_secs = 45.0
color = [39, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_grasping_slam_1st"
name = "Grasping Slam 1st"
trigger = { type = "effect_applied", effect_ids = [3009973210578944] }
duration_secs = 13.0
color = [224, 29, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_spit_pool_scream_1st"
name = "Spit Pool + Scream 1st"
trigger = { type = "effect_applied", effect_ids = [3009973210578944] }
duration_secs = 42.0
color = [228, 127, 40, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_terror_from_beyond_void_disturbance_buf"
name = "Void Disturbance BUF"
trigger = { type = "effect_applied", effect_ids = [3246243656499200] }
duration_secs = 20.0
color = [222, 26, 32, 255]
difficulties = ["veteran", "master"]

# ─── the_writhing_horror ───
[[boss]]
id = "the_writhing_horror"
name = "The Writhing Horror"
difficulties = ["master", "veteran"]
npc_names = ["The Writhing Horror"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_writhing_horror_teleport_1st"
name = "Teleport 1st"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [26, 220, 212, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_writhing_horror_teleport"
name = "Teleport"
trigger = { type = "ability_cast", ability_ids = [3016484380999680] }
duration_secs = 45.0
color = [26, 220, 212, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_writhing_horror_male_puddle_1st"
name = "Male + Puddle 1st"
trigger = { type = "combat_start" }
duration_secs = 45.0
color = [197, 17, 188, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_writhing_horror_male_puddle"
name = "Male + Puddle_"
trigger = { type = "timer_expires", timer_id = "the_writhing_horror_male_puddle_2" }
duration_secs = 90.0
color = [197, 17, 188, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_writhing_horror_male_puddle_2"
name = "Male + Puddle"
trigger = { type = "timer_expires", timer_id = "the_writhing_horror_male_puddle_1st" }
duration_secs = 90.0
color = [197, 17, 188, 255]
difficulties = ["veteran", "master"]
