# The Dread Fortress
# 5 boss(es)

[area]
name = "The Dread Fortress"
area_id = 137438993402

# ─── corruptor_zero ───
[[boss]]
id = "corruptor_zero"
name = "Corruptor Zero"
difficulties = ["master", "veteran"]
npc_names = ["Corruptor Zero"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "corruptor_zero_burn_phase"
name = "Burn Phase"
trigger = { type = "effect_applied", effect_ids = [3287793170121044] }
duration_secs = 33.5
color = [133, 56, 85, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_missile_barrage"
name = "Missile Barrage"
trigger = { type = "ability_cast", ability_ids = [3286483205095424] }
duration_secs = 15.0
color = [35, 28, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_heavy_slash"
name = "Heavy Slash"
trigger = { type = "ability_cast", ability_ids = [3286530449735680] }
duration_secs = 20.0
color = [219, 30, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_chest_laser"
name = "Chest Laser"
trigger = { type = "ability_cast", ability_ids = [3285409463271424] }
duration_secs = 15.0
color = [224, 59, 212, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_beam_melee_mode"
name = "Beam (Melee Mode)"
trigger = { type = "effect_applied", effect_ids = [3284760923209993] }
duration_secs = 60.0
color = [219, 96, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_gravity_ranged_mode"
name = "Gravity (Ranged Mode)"
trigger = { type = "effect_applied", effect_ids = [3284760923209990] }
duration_secs = 60.0
color = [219, 96, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_concussion_mine"
name = "Concussion Mine"
trigger = { type = "ability_cast", ability_ids = [3321882325549056] }
duration_secs = 21.5
color = [24, 224, 221, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_gravity_delay"
name = "Gravity Delay"
trigger = { type = "ability_cast", ability_ids = [3321882325549056] }
duration_secs = 11.5
color = [204, 191, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_gravity_field"
name = "Gravity Field"
trigger = { type = "ability_cast", ability_ids = [3285972103987200] }
duration_secs = 33.0
color = [204, 191, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_beams_x_4"
name = "Beams x 4"
trigger = { type = "timer_expires", timer_id = "0e645f60-5ede-4a6c-8b95-344e1386dcec" }
duration_secs = 20.0
color = [133, 56, 85, 255]
difficulties = ["veteran", "master"]

# ─── dread_master_brontes ───
[[boss]]
id = "dread_master_brontes"
name = "Dread Master Brontes"
difficulties = ["master", "veteran"]
npc_names = ["Dread Master Brontes"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "dread_master_brontes_clone"
name = "Clone"
trigger = { type = "ability_cast", ability_ids = [3309152042483712] }
duration_secs = 30.0
color = [32, 168, 18, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_overcharge_1st"
name = "Overcharge 1st"
trigger = { type = "ability_cast", ability_ids = [3313824966901760] }
duration_secs = 30.0
color = [36, 32, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_fingers_knockback_1st"
name = "Fingers Knockback 1st"
trigger = { type = "ability_cast", ability_ids = [3303572879966208] }
duration_secs = 12.0
color = [224, 38, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_energy_sphere_p3"
name = "Energy Sphere P3"
trigger = { type = "ability_cast", ability_ids = [3313167836905472] }
duration_secs = 12.0
color = [219, 31, 28, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_overcharge"
name = "Overcharge"
trigger = { type = "ability_cast", ability_ids = [3313528614158336] }
duration_secs = 16.0
color = [36, 28, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_fingers_knockback"
name = "Fingers Knockback"
trigger = { type = "timer_expires", timer_id = "dread_master_brontes_fingers_knockback_1st" }
duration_secs = 30.0
color = [219, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_fingers_knockback_2"
name = "Fingers Knockback_"
trigger = { type = "timer_expires", timer_id = "dread_master_brontes_fingers_knockback" }
duration_secs = 30.0
color = [224, 34, 29, 255]
difficulties = ["veteran", "master"]

# ─── gate_commander_draxus ───
[[boss]]
id = "gate_commander_draxus"
name = "Gate Commander Draxus"
difficulties = ["master"]
npc_names = ["Gate Commander Draxus"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gate_commander_draxus_adds_w1"
name = "Adds W1"
trigger = { type = "combat_start" }
duration_secs = 50.0
color = [33, 151, 18, 255]
difficulties = ["master"]

# ─── grob_thok_who_feeds_the_forge ───
[[boss]]
id = "grob_thok_who_feeds_the_forge"
name = "Grob'thok, Who Feeds the Forge"
difficulties = ["master", "veteran"]
npc_names = ["Grob'thok, Who Feeds the Forge"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_pipe_smash_1st"
name = "Pipe Smash 1st"
trigger = { type = "combat_start" }
duration_secs = 60.0
color = [204, 182, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_pipe_smash"
name = "Pipe Smash"
trigger = { type = "ability_cast", ability_ids = [3307601559289856] }
duration_secs = 63.0
color = [204, 182, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3315585903493120] }
duration_secs = 25.0
color = [25, 148, 13, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_lava_dot"
name = "Lava DOT"
trigger = { type = "ability_cast", ability_ids = [3294703772499968] }
duration_secs = 30.0
color = [224, 108, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_overhead_smash"
name = "Overhead Smash"
trigger = { type = "ability_cast", ability_ids = [3285993578823680] }
duration_secs = 33.0
color = [144, 24, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_roar"
name = "Roar"
trigger = { type = "ability_cast", ability_ids = [3285997873790976] }
duration_secs = 15.0
color = [219, 28, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_stunned"
name = "Stunned"
trigger = { type = "effect_applied", effect_ids = [3286745198100740] }
duration_secs = 10.0
color = [33, 224, 221, 255]
difficulties = ["veteran", "master"]

# ─── nefra_who_bars_the_way ───
[[boss]]
id = "nefra_who_bars_the_way"
name = "Nefra, Who Bars the Way"
difficulties = ["master", "veteran"]
npc_names = ["Nefra, Who Bars the Way"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "nefra_who_bars_the_way_voice_of_the_masters_1st"
name = "Voice of the Masters 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [29, 153, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_voice_of_the_masters"
name = "Voice of the Masters"
trigger = { type = "ability_cast", ability_ids = [3270007710547968] }
duration_secs = 30.0
color = [29, 153, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_dps_add_1st"
name = "DPS Add 1st"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [37, 219, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_tank_add_1st"
name = "TANK Add 1st"
trigger = { type = "combat_start" }
duration_secs = 45.0
color = [52, 28, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "nefra_who_bars_the_way_dps_add_vm"
name = "DPS Add VM"
trigger = { type = "ability_cast", ability_ids = [3308460552749056] }
duration_secs = 30.0
color = [32, 211, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "nefra_who_bars_the_way_tank_add_vm"
name = "TANK Add VM"
trigger = { type = "ability_cast", ability_ids = [3308164200005632] }
duration_secs = 30.0
color = [46, 32, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "nefra_who_bars_the_way_tank_add"
name = "TANK Add"
trigger = { type = "ability_cast", ability_ids = [3308460552749056] }
duration_secs = 10.0
color = [33, 29, 224, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_dps_add"
name = "DPS Add"
trigger = { type = "ability_cast", ability_ids = [3308164200005632] }
duration_secs = 10.0
color = [32, 219, 213, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_rng_add"
name = "RNG Add"
trigger = { type = "ability_cast", ability_ids = [3342034312101888] }
duration_secs = 30.0
color = [33, 149, 224, 255]
difficulties = ["master"]
