# The Ravagers
# 5 boss(es)

[area]
name = "The Ravagers"
area_id = 3367421863788544

# ─── coratanni ───
[[boss]]
id = "coratanni"
name = "Coratanni"
difficulties = ["master", "veteran"]
npc_names = ["Coratanni"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "coratanni_ricochet_1st"
name = "Ricochet 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [224, 32, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_ricochet"
name = "Ricochet"
trigger = { type = "ability_cast", ability_ids = [3372880767221760] }
duration_secs = 15.0
color = [219, 29, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_cannon_shot"
name = "Cannon Shot"
trigger = { type = "ability_cast", ability_ids = [3374298106429440] }
duration_secs = 20.0
color = [128, 189, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_multi_charge_1st"
name = "Multi Charge 1st"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [177, 32, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_cannon_shot_1st"
name = "Cannon Shot 1st"
trigger = { type = "combat_start" }
duration_secs = 35.0
color = [128, 189, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_focus"
name = "Focus"
trigger = { type = "ability_cast", ability_ids = [3438829990051840] }
duration_secs = 40.0
color = [141, 29, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [3378185051832320] }
duration_secs = 30.0
color = [13, 103, 51, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_cull"
name = "Cull"
trigger = { type = "ability_cast", ability_ids = [3438778450444288] }
duration_secs = 20.0
color = [25, 114, 194, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_death_mouse"
name = "Death Mouse"
trigger = { type = "ability_cast", ability_ids = [3438825695084544] }
duration_secs = 20.0
color = [28, 184, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_hostage"
name = "Hostage"
trigger = { type = "ability_cast", ability_ids = [3438765565542400] }
duration_secs = 60.0
color = [219, 26, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_aoe_knockback_rng"
name = "AoE knockback(RNG)"
trigger = { type = "ability_cast", ability_ids = [3514734947074048] }
duration_secs = 15.0
color = [224, 113, 33, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_jest_boost"
name = "Jest Boost_"
trigger = { type = "ability_cast", ability_ids = [3378167871963136] }
duration_secs = 15.6
color = [224, 113, 33, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_jet_boost"
name = "Jet Boost"
trigger = { type = "timer_expires", timer_id = "coratanni_aoe_knockback_rng" }
duration_secs = 15.0
color = [224, 113, 33, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "coratanni_can_t_grapple"
name = "Can't Grapple"
trigger = { type = "ability_cast", ability_ids = [3441853647028224] }
duration_secs = 5.0
color = [32, 35, 219, 255]
difficulties = ["veteran", "master"]

# ─── master_blaster ───
[[boss]]
id = "master_blaster"
name = "Master & Blaster"
difficulties = ["veteran"]
npc_names = ["Master & Blaster"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "master_blaster_2n_rop_dmg"
name = "2n ROP DMG"
trigger = { type = "timer_expires", timer_id = "master_blaster_1st_rop_dmg" }
duration_secs = 9.0
color = [224, 33, 187, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_3rd_rop_dmg"
name = "3rd ROP DMG"
trigger = { type = "timer_expires", timer_id = "master_blaster_2n_rop_dmg" }
duration_secs = 9.0
color = [224, 33, 187, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_rop_shield_down"
name = "ROP Shield down"
trigger = { type = "timer_expires", timer_id = "master_blaster_3rd_rop_dmg" }
duration_secs = 6.0
color = [224, 33, 187, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_rain_of_pain"
name = "Rain of Pain"
trigger = { type = "timer_expires", timer_id = "master_blaster_rop_shield_down" }
duration_secs = 49.4
color = [224, 33, 187, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_scatterblast_1st"
name = "Scatterblast 1st"
trigger = { type = "combat_start" }
duration_secs = 6.0
color = [219, 28, 28, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_fire_wheel"
name = "Fire Wheel"
trigger = { type = "timer_expires", timer_id = "master_blaster_ion_cutter" }
duration_secs = 20.0
color = [224, 131, 33, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_ion_cutter"
name = "Ion Cutter"
trigger = { type = "ability_cast", ability_ids = [3397933311459328] }
duration_secs = 12.0
color = [33, 224, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_rain_of_pain_1st"
name = "Rain of Pain 1st"
trigger = { type = "effect_removed", effect_ids = [3413408078626816] }
duration_secs = 59.0
color = [224, 24, 191, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_1st_rop_dmg"
name = "1st ROP DMG"
trigger = { type = "ability_cast", ability_ids = [3400759399940096] }
duration_secs = 11.6
color = [224, 33, 187, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_scatterblast_m"
name = "Scatterblast M"
trigger = { type = "ability_cast", ability_ids = [3421916408840192] }
duration_secs = 9.0
color = [219, 28, 28, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_scatterblast_p1"
name = "Scatterblast P1"
trigger = { type = "ability_cast", ability_ids = [3393552444817408] }
duration_secs = 9.0
color = [219, 28, 28, 255]
phases = ["p1"]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_scatterblast_p2_1st"
name = "Scatterblast P2 1st"
trigger = { type = "effect_removed", effect_ids = [3413408078626816] }
duration_secs = 13.0
color = [219, 32, 34, 255]
phases = ["p2"]
difficulties = ["veteran"]

[[boss.timer]]
id = "master_blaster_scatterblast_p2"
name = "Scatterblast P2"
trigger = { type = "ability_cast", ability_ids = [3393552444817408] }
duration_secs = 18.0
color = [220, 42, 39, 255]
phases = ["p2"]
difficulties = ["veteran"]

# ─── quartermaster_bulo ───
[[boss]]
id = "quartermaster_bulo"
name = "Quartermaster Bulo"
difficulties = ["master", "veteran"]
npc_names = ["Quartermaster Bulo"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "quartermaster_bulo_shotgun_blast_1st"
name = "Shotgun Blast 1st"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [210, 24, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_shotgun_blast"
name = "Shotgun Blast"
trigger = { type = "ability_cast", ability_ids = [3391714198814720] }
duration_secs = 8.5
color = [210, 24, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_gcd"
name = "GCD"
trigger = { type = "ability_cast", ability_ids = [3396090770489344] }
duration_secs = 4.0
color = [29, 224, 221, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_pirates"
name = "Pirates"
trigger = { type = "ability_cast", ability_ids = [3391757148487680] }
duration_secs = 45.0
color = [38, 168, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_pirates_1st"
name = "Pirates 1st"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [38, 168, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_volley"
name = "Volley"
trigger = { type = "ability_cast", ability_ids = [3391752853520384] }
duration_secs = 18.0
color = [34, 29, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_volley_1st"
name = "Volley 1st"
trigger = { type = "combat_start" }
duration_secs = 14.0
color = [34, 29, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_carts"
name = "Carts"
trigger = { type = "ability_cast", ability_ids = [3466880421462016] }
duration_secs = 45.0
color = [167, 179, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_loadlifters"
name = "Loadlifters"
trigger = { type = "ability_cast", ability_ids = [3420554904207360] }
duration_secs = 30.0
color = [28, 78, 48, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_barrel_throw"
name = "Barrel Throw"
trigger = { type = "timer_expires", timer_id = "quartermaster_bulo_gcd" }
duration_secs = 6.0
color = [146, 33, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_scatter_blaster_end"
name = "Scatter Blaster END"
trigger = { type = "ability_cast", ability_ids = [3391744263585792] }
duration_secs = 11.0
color = [224, 29, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_scatter_blaster"
name = "Scatter Blaster"
trigger = { type = "timer_expires", timer_id = "quartermaster_bulo_scatter_blaster_end" }
duration_secs = 29.0
color = [219, 38, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_carts_scatter"
name = "Carts+Scatter"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [224, 25, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_barrage_carts_delay"
name = "Barrage/Carts delay"
trigger = { type = "ability_cast", ability_ids = [3391744263585792] }
duration_secs = 20.0
color = [167, 179, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_mass_barrage_end"
name = "Mass Barrage END"
trigger = { type = "ability_cast", ability_ids = [3417496887492608] }
duration_secs = 13.0
color = [224, 110, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_mass_barrage"
name = "Mass Barrage"
trigger = { type = "timer_expires", timer_id = "quartermaster_bulo_mass_barrage_end" }
duration_secs = 50.0
color = [224, 110, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_relocated"
name = "Relocated"
trigger = { type = "ability_cast", ability_ids = [3457169500405760] }
duration_secs = 45.0
color = [28, 219, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "quartermaster_bulo_relocate_barrage"
name = "Relocate+Barrage"
trigger = { type = "combat_start" }
duration_secs = 50.0
color = [37, 224, 218, 255]
difficulties = ["veteran", "master"]

# ─── sparky ───
[[boss]]
id = "sparky"
name = "Sparky"
difficulties = ["master", "veteran"]
npc_names = ["Sparky"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "sparky_shoulder_throw"
name = "Shoulder Throw"
trigger = { type = "ability_cast", ability_ids = [3377850044383232] }
duration_secs = 13.0
color = [203, 204, 46, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_rampage_end"
name = "Rampage END"
trigger = { type = "ability_cast", ability_ids = [3380452794564608] }
duration_secs = 15.0
color = [187, 29, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_rampage_p2"
name = "Rampage P2"
trigger = { type = "timer_expires", timer_id = "sparky_rampage_end" }
duration_secs = 36.0
color = [187, 29, 224, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_body_slam"
name = "Body Slam_"
trigger = { type = "ability_cast", ability_ids = [3377991778304000] }
duration_secs = 13.0
color = [224, 29, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_body_slam_2"
name = "Body Slam"
trigger = { type = "ability_cast", ability_ids = [3377850044383232] }
duration_secs = 25.0
color = [219, 34, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_rampage_p3"
name = "Rampage P3"
trigger = { type = "timer_expires", timer_id = "sparky_rampage_end" }
duration_secs = 46.0
color = [187, 29, 224, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_forceful_roar_adds"
name = "Forceful Roar (Adds)"
trigger = { type = "ability_cast", ability_ids = [3380792096980992] }
duration_secs = 40.5
color = [34, 173, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sparky_roar_adds"
name = "Roar (Adds)"
trigger = { type = "ability_cast", ability_ids = [3378502879412224] }
duration_secs = 17.5
color = [34, 173, 19, 255]
difficulties = ["veteran", "master"]

# ─── torque ───
[[boss]]
id = "torque"
name = "Torque"
difficulties = ["master", "veteran"]
npc_names = ["Torque"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "torque_magnetic_1st"
name = "Magnetic 1st"
trigger = { type = "timer_expires", timer_id = "16f30336-e475-4b54-ae80-f63868d8d46e" }
duration_secs = 5.0
color = [28, 219, 215, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_magnetic_clamp"
name = "Magnetic Clamp"
trigger = { type = "ability_cast", ability_ids = [3430678142124032] }
duration_secs = 30.0
color = [33, 224, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_laser_turret_1st"
name = "Laser Turret 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [138, 98, 48, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_flame_turret"
name = "Flame Turret"
trigger = { type = "ability_cast", ability_ids = [3406531835985920] }
duration_secs = 15.0
color = [219, 189, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_laser_turret"
name = "Laser Turret"
trigger = { type = "ability_cast", ability_ids = [3406527541018624] }
duration_secs = 15.0
color = [138, 98, 48, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_vents_knockback"
name = "Vents + Knockback"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [219, 32, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [3409211895578624] }
duration_secs = 40.0
color = [219, 105, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_vents"
name = "Vents"
trigger = { type = "ability_cast", ability_ids = [3406488886312960] }
duration_secs = 30.0
color = [219, 29, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_jump_to_console"
name = "Jump to Console"
trigger = { type = "ability_cast", ability_ids = [3412583444905984] }
duration_secs = 45.0
color = [31, 153, 14, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_jump_to_console_1st"
name = "Jump to Console 1st"
trigger = { type = "combat_start" }
duration_secs = 40.0
color = [31, 153, 14, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_side_turrets_1st"
name = "Side Turrets 1st"
trigger = { type = "combat_start" }
duration_secs = 50.0
color = [25, 23, 214, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "torque_side_turrets"
name = "Side Turrets"
trigger = { type = "ability_cast", ability_ids = [3513382032375808] }
duration_secs = 60.0
color = [40, 28, 219, 255]
difficulties = ["veteran", "master"]
