# The Gods from the Machine
# 5 boss(es)

[area]
name = "The Gods from the Machine"
area_id = 833571547775765

# ─── aivela_and_esne ───
[[boss]]
id = "aivela_and_esne"
name = "Aivela and Esne"
difficulties = ["master", "veteran"]
npc_names = ["Aivela and Esne"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "aivela_and_esne_synergy_protocol"
name = "Synergy Protocol"
trigger = { type = "ability_cast", ability_ids = [4111769760956416] }
duration_secs = 32.0
color = [219, 28, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_gcd"
name = "Purification GCD"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_purification_p3_1st" }
duration_secs = 27.0
color = [224, 24, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_p3"
name = "Purification P3"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_purification_gcd" }
duration_secs = 9.0
color = [224, 31, 29, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_empowered_shield"
name = "Empowered Shield"
trigger = { type = "effect_removed", effect_ids = [4112590099709952] }
duration_secs = 16.0
color = [188, 194, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_synergy_protocol_1st"
name = "Synergy Protocol 1st"
trigger = { type = "timer_expires", timer_id = "49b21a3a-b481-4cc8-b59a-40fbec336f08" }
duration_secs = 18.0
color = [224, 36, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_p3_1st"
name = "Purification P3 1st"
trigger = { type = "timer_expires", timer_id = "80846669-b7aa-4e20-8f83-a01063020943" }
duration_secs = 12.0
color = [224, 29, 29, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_p4_1st"
name = "Purification P4 1st"
trigger = { type = "timer_expires", timer_id = "61aef9a6-418c-49f5-a43d-b77a1a60b256" }
duration_secs = 12.0
color = [224, 34, 29, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_p4_d"
name = "Purification P4 (D)"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_purification_gcd" }
duration_secs = 10.0
color = [224, 33, 34, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_p4"
name = "Purification P4"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_purification_p4_1st" }
duration_secs = 30.0
color = [219, 24, 27, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_purification_p4_loop"
name = "Purification P4_LOOP"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_purification_p4" }
duration_secs = 30.0
color = [219, 30, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "aivela_and_esne_1st_invul"
name = "1st Invul"
trigger = { type = "timer_expires", timer_id = "5d06e766-1ae9-49da-82a1-42cb91363965" }
duration_secs = 15.0
color = [29, 163, 21, 255]
difficulties = ["master"]

[[boss.timer]]
id = "aivela_and_esne_2nd_jump"
name = "2nd Jump"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_1st_invul" }
duration_secs = 45.0
color = [29, 163, 21, 255]
difficulties = ["master"]

[[boss.timer]]
id = "aivela_and_esne_2nd_invul"
name = "2nd Invul"
trigger = { type = "timer_expires", timer_id = "aivela_and_esne_2nd_jump" }
duration_secs = 15.0
color = [29, 163, 21, 255]
difficulties = ["master"]

# ─── izax ───
[[boss]]
id = "izax"
name = "IZAX"
difficulties = ["master", "veteran"]
npc_names = ["IZAX"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "izax_induction"
name = "Induction"
trigger = { type = "ability_cast", ability_ids = [4168128321814528] }
duration_secs = 34.0
color = [38, 210, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p4_reposition_1st_m"
name = "P4 Reposition 1st_M"
trigger = { type = "effect_applied", effect_ids = [4173226447994880] }
duration_secs = 80.0
color = [205, 30, 177, 255]
phases = ["p4"]
difficulties = ["master"]

[[boss.timer]]
id = "izax_p4_missile_volley_1"
name = "P4 Missile Volley 1"
trigger = { type = "ability_cast", ability_ids = [4163854829355008] }
duration_secs = 13.0
color = [220, 37, 32, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p4_missile_volley_2"
name = "P4 Missile Volley 2"
trigger = { type = "timer_expires", timer_id = "izax_p4_missile_volley_1" }
duration_secs = 11.0
color = [220, 38, 32, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p4_missile_volley_3"
name = "P4 Missile Volley 3"
trigger = { type = "timer_expires", timer_id = "izax_p4_missile_volley_2" }
duration_secs = 11.0
color = [220, 31, 26, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p4_missile_volley_4"
name = "P4 Missile Volley 4"
trigger = { type = "timer_expires", timer_id = "izax_p4_missile_volley_3" }
duration_secs = 11.0
color = [220, 32, 34, 255]
phases = ["p4"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p5_scyva"
name = "P5 SCYVA"
trigger = { type = "timer_expires", timer_id = "izax_p4_missile_volley_4" }
duration_secs = 11.0
color = [18, 201, 205, 255]
phases = ["p5"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p5_end"
name = "P5 End"
trigger = { type = "timer_expires", timer_id = "izax_p5_scyva" }
duration_secs = 120.0
color = [32, 220, 220, 255]
phases = ["p5"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p5_explosion"
name = "P5 Explosion"
trigger = { type = "timer_expires", timer_id = "izax_p5_end" }
duration_secs = 10.0
color = [220, 36, 32, 255]
phases = ["p5"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p6_wipe"
name = "P6 Wipe"
trigger = { type = "timer_expires", timer_id = "izax_p6_radiation" }
duration_secs = 22.0
color = [220, 40, 32, 255]
phases = ["p6"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p3_shield_down"
name = "P3 Shield Down"
trigger = { type = "effect_removed", effect_ids = [4162922821451776] }
duration_secs = 12.0
color = [20, 159, 19, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p3_tether_droids"
name = "P3 Tether Droids"
trigger = { type = "timer_expires", timer_id = "70103fbf-2538-4b50-94ca-1276a733619d" }
duration_secs = 5.0
color = [220, 37, 32, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p4_reposition_m"
name = "P4 Reposition_M"
trigger = { type = "ability_cast", ability_ids = [4166341615419392] }
duration_secs = 80.0
color = [213, 31, 186, 255]
phases = ["p4"]
difficulties = ["master"]

[[boss.timer]]
id = "izax_p2_hull_cutters"
name = "P2 Hull Cutters"
trigger = { type = "ability_cast", ability_ids = [4160719503228928] }
duration_secs = 36.0
color = [205, 173, 30, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p2_explosion_1"
name = "P2 Explosion 1"
trigger = { type = "ability_cast", ability_ids = [4168794041745408] }
duration_secs = 12.0
color = [205, 118, 30, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p2_explosion_2"
name = "P2 Explosion 2"
trigger = { type = "timer_expires", timer_id = "izax_p2_explosion_1" }
duration_secs = 7.0
color = [205, 118, 30, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p2_knockback"
name = "P2 Knockback"
trigger = { type = "effect_applied", effect_ids = [4161715935641600] }
duration_secs = 15.0
color = [220, 33, 32, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p1_slam"
name = "P1 Slam"
trigger = { type = "combat_start" }
duration_secs = 26.0
color = [31, 213, 212, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "izax_p6_radiation"
name = "P6 Radiation"
trigger = { type = "effect_applied", effect_ids = [4168746797105152] }
duration_secs = 28.0
color = [213, 43, 38, 255]
phases = ["p6"]
difficulties = ["veteran", "master"]

# ─── nahut ───
[[boss]]
id = "nahut"
name = "NAHUT"
difficulties = ["master"]
npc_names = ["NAHUT"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "nahut_discharge_1st"
name = "Discharge 1st"
trigger = { type = "ability_cast", ability_ids = [4133906022400000] }
duration_secs = 12.0
color = [23, 37, 232, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_slice"
name = "Slice"
trigger = { type = "ability_cast", ability_ids = [4137075708264448] }
duration_secs = 12.0
color = [208, 16, 17, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_suppression"
name = "Suppression"
trigger = { type = "ability_cast", ability_ids = [4181850742325248] }
duration_secs = 16.0
color = [227, 106, 31, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_mass_distortion_p1"
name = "Mass Distortion P1"
trigger = { type = "ability_cast", ability_ids = [4126462844076032] }
duration_secs = 11.0
color = [153, 27, 227, 255]
phases = ["p1"]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_turret_spawn"
name = "Turret Spawn"
trigger = { type = "ability_cast", ability_ids = [4134120770764800] }
duration_secs = 40.0
color = [102, 71, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_turrets_1st"
name = "Turrets 1st"
trigger = { type = "effect_removed", effect_ids = [4134133655667051] }
duration_secs = 10.0
color = [102, 71, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_suppression_cd"
name = "Suppression CD"
trigger = { type = "ability_cast", ability_ids = [4181850742325248] }
duration_secs = 60.5
color = [204, 192, 46, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_mass_distortion"
name = "Mass Distortion"
trigger = { type = "ability_cast", ability_ids = [4124212281212928] }
duration_secs = 12.5
color = [142, 30, 222, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_mass_distortion_p3"
name = "Mass Distortion P3"
trigger = { type = "effect_removed", effect_ids = [4134133655667051] }
duration_secs = 12.0
color = [154, 30, 222, 255]
phases = ["p3"]
difficulties = ["master"]

# ─── scyva ───
[[boss]]
id = "scyva"
name = "SCYVA"
difficulties = ["master", "veteran"]
npc_names = ["SCYVA"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "scyva_p1_beams_1st"
name = "P1 Beams 1st"
trigger = { type = "combat_start" }
duration_secs = 4.0
color = [22, 173, 45, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_p1_beams"
name = "P1 Beams_"
trigger = { type = "timer_expires", timer_id = "scyva_p1_beams_2" }
duration_secs = 15.0
color = [36, 168, 25, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_p1_beams_2"
name = "P1 Beams"
trigger = { type = "timer_expires", timer_id = "scyva_p1_beams_1st" }
duration_secs = 15.0
color = [36, 168, 25, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_upheaval"
name = "Upheaval"
trigger = { type = "ability_cast", ability_ids = [4127296067731456] }
duration_secs = 15.0
color = [189, 182, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_red_catalyst_1st"
name = "Red Catalyst 1st"
trigger = { type = "timer_expires", timer_id = "e3ee3b94-2c94-4880-be59-dd6e70550437" }
duration_secs = 12.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_double_catalyst_1st"
name = "Double Catalyst 1st"
trigger = { type = "timer_expires", timer_id = "scyva_red_catalyst_1st" }
duration_secs = 12.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_red_catalyst_2nd"
name = "Red Catalyst 2nd"
trigger = { type = "timer_expires", timer_id = "scyva_double_catalyst_1st" }
duration_secs = 12.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_5th_beam"
name = "5th Beam"
trigger = { type = "timer_expires", timer_id = "scyva_red_catalyst_2nd" }
duration_secs = 12.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_double_catalyst_2nd"
name = "Double Catalyst 2nd"
trigger = { type = "timer_expires", timer_id = "scyva_5th_beam" }
duration_secs = 12.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_7th_beam"
name = "7th Beam"
trigger = { type = "timer_expires", timer_id = "scyva_double_catalyst_2nd" }
duration_secs = 12.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_scyva_vulnarable"
name = "SCYVA Vulnarable"
trigger = { type = "timer_expires", timer_id = "scyva_7th_beam" }
duration_secs = 68.0
color = [224, 31, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_expansion_p5"
name = "Expansion P5"
trigger = { type = "effect_applied", effect_ids = [4132067776397621] }
duration_secs = 13.0
color = [224, 32, 29, 255]
phases = ["p5"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_atomic_p5_1st"
name = "Atomic P5 1st"
trigger = { type = "ability_cast", ability_ids = [4146653485334528] }
duration_secs = 13.0
color = [220, 43, 32, 255]
phases = ["p5"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "scyva_iginte_core"
name = "Iginte Core"
trigger = { type = "effect_applied", effect_ids = [4131775718621461] }
duration_secs = 50.0
color = [222, 74, 30, 255]
difficulties = ["veteran", "master"]

# ─── tyth ───
[[boss]]
id = "tyth"
name = "TYTH"
difficulties = ["master"]
npc_names = ["TYTH"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "tyth_adds_setup"
name = "Adds setup"
trigger = { type = "timer_expires", timer_id = "tyth_adds" }
duration_secs = 17.0
color = [54, 214, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4076168777039872] }
duration_secs = 15.0
color = [54, 214, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_inversion_1st"
name = "Inversion 1st"
trigger = { type = "combat_start" }
duration_secs = 21.0
color = [184, 29, 224, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_inversion"
name = "Inversion"
trigger = { type = "ability_cast", ability_ids = [4071117895499776] }
duration_secs = 37.0
color = [184, 29, 224, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_energy_wave"
name = "Energy Wave"
trigger = { type = "ability_cast", ability_ids = [4081339917664256] }
duration_secs = 12.0
color = [224, 29, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_sweep"
name = "Sweep"
trigger = { type = "ability_cast", ability_ids = [4080279060742144] }
duration_secs = 6.0
color = [214, 108, 32, 255]
difficulties = ["master"]
