# Toborro's Palace
# 1 boss(es)

[area]
name = "Toborro's Palace"
area_id = 0

# ─── golden_fury ───
[[boss]]
id = "golden_fury"
name = "Golden Fury"
difficulties = ["veteran"]
npc_names = ["Golden Fury"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "golden_fury_laser"
name = "Laser"
trigger = { type = "ability_cast", ability_ids = [3258922399956992] }
duration_secs = 45.0
color = [219, 32, 32, 255]
difficulties = ["veteran"]
