# Commander Jensyn - Korriban Incursion
# Auto-converted from Orbs timers

[[boss]]
id = "commander_jensyn"
name = "Commander Jensyn"
area_name = "Korriban Incursion"
difficulties = ["master", "veteran"]
npc_names = ["Commander Jensyn"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_jensyn_master_strike"
name = "Master Strike_"
trigger = { type = "ability_cast", ability_ids = [3333800859795456] }
duration_secs = 7.0
color = [32, 217, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_reflect_permision"
name = "Reflect Permision"
trigger = { type = "ability_cast", ability_ids = [3334715687829504] }
duration_secs = 16.0
color = [186, 197, 23, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_stun_add"
name = "Stun Add"
trigger = { type = "timer_expires", timer_id = "commander_jensyn_reflect_permision" }
duration_secs = 44.0
color = [19, 121, 18, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add_setup"
name = "Suicide Add Setup"
trigger = { type = "ability_cast", ability_ids = [3486143349784576] }
duration_secs = 5.0
color = [228, 137, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add"
name = "Suicide Add"
trigger = { type = "timer_expires", timer_id = "commander_jensyn_suicide_add_setup" }
duration_secs = 10.0
color = [220, 138, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add_2"
name = "Suicide Add_"
trigger = { type = "ability_cast", ability_ids = [3332641218625536] }
duration_secs = 10.0
color = [228, 138, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_suicide_add_3"
name = "Suicide Add__"
trigger = { type = "effect_removed", effect_ids = [3334857421750272] }
duration_secs = 10.0
color = [220, 125, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_jensyn_master_strike_2"
name = "Master Strike"
trigger = { type = "ability_cast", ability_ids = [3333289758687232] }
duration_secs = 15.0
color = [27, 208, 228, 255]
difficulties = ["veteran", "master"]
