# Republic Commander - Korriban Incursion
# Auto-converted from Orbs timers

[[boss]]
id = "republic_commander"
name = "Republic Commander"
area_name = "Korriban Incursion"
difficulties = ["master", "veteran"]
npc_names = ["Republic Commander"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "republic_commander_force_push"
name = "Force Push"
trigger = { type = "ability_cast", ability_ids = [3493260110594048] }
duration_secs = 10.0
color = [192, 27, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_master_strike"
name = "Master Strike"
trigger = { type = "ability_cast", ability_ids = [3493272995495936] }
duration_secs = 30.0
color = [220, 31, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_master_stasis"
name = "Master Stasis"
trigger = { type = "ability_cast", ability_ids = [3493247225692160] }
duration_secs = 32.0
color = [31, 202, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_shockwave"
name = "Shockwave"
trigger = { type = "ability_cast", ability_ids = [811976452210688] }
duration_secs = 30.0
color = [213, 201, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "republic_commander_hilt_strike"
name = "Hilt Strike"
trigger = { type = "ability_cast", ability_ids = [3493277290463232] }
duration_secs = 30.0
color = [220, 128, 39, 255]
difficulties = ["veteran", "master"]
