# HK-47 - The False Emperor
# Auto-converted from Orbs timers

[[boss]]
id = "hk_47"
name = "HK-47"
area_name = "The False Emperor"
difficulties = ["master", "veteran"]
npc_names = ["HK-47"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "hk_47_sonic_grenade_p1"
name = "Sonic Grenade P1"
trigger = { type = "timer_expires", timer_id = "988c5115-ac13-4c6d-b19e-f3e55f66e2ac" }
duration_secs = 5.0
color = [220, 215, 32, 255]
phases = ["p1"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_sonic_grenade_p2"
name = "Sonic Grenade P2"
trigger = { type = "timer_expires", timer_id = "200d363c-a47c-43db-8cab-e176d7b0f55d" }
duration_secs = 3.0
color = [220, 206, 39, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_snipe_p2"
name = "Snipe P2"
trigger = { type = "timer_expires", timer_id = "hk_47_sonic_grenade_p2" }
duration_secs = 6.0
color = [220, 32, 122, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_poison_grenade_p2"
name = "Poison Grenade P2"
trigger = { type = "timer_expires", timer_id = "hk_47_snipe_p2" }
duration_secs = 3.0
color = [30, 174, 26, 255]
phases = ["p2"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_snipe"
name = "Snipe"
trigger = { type = "ability_cast", ability_ids = [2472432283680768] }
duration_secs = 35.0
color = [220, 32, 145, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_burst"
name = "Burst"
trigger = { type = "ability_cast", ability_ids = [2061614366851072] }
duration_secs = 10.0
color = [220, 37, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_sonic_grenade"
name = "Sonic Grenade"
trigger = { type = "ability_cast", ability_ids = [2058255702425600] }
duration_secs = 15.0
color = [205, 202, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hk_47_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 160.0
color = [37, 27, 228, 255]
difficulties = ["master"]
