# Jindo Krey - The False Emperor
# Auto-converted from Orbs timers

[[boss]]
id = "jindo_krey"
name = "Jindo Krey"
area_name = "The False Emperor"
difficulties = ["master", "veteran"]
npc_names = ["Jindo Krey"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "jindo_krey_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [1626349496172544] }
duration_secs = 32.0
color = [32, 81, 182, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_rail_shot"
name = "Rail Shot"
trigger = { type = "ability_cast", ability_ids = [1626413920681984] }
duration_secs = 15.0
color = [98, 136, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_jet_charge"
name = "Jet Charge"
trigger = { type = "ability_cast", ability_ids = [1626899251986432] }
duration_secs = 12.0
color = [190, 87, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_missile_barrage"
name = "Missile Barrage"
trigger = { type = "ability_cast", ability_ids = [1593385622175744] }
duration_secs = 39.0
color = [236, 20, 0, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "jindo_krey_missile_blast"
name = "Missile Blast"
trigger = { type = "ability_cast", ability_ids = [1593381327208448] }
duration_secs = 12.0
color = [190, 11, 180, 255]
difficulties = ["veteran", "master"]
