# Prototype A-14 & Prototype B-16 - The False Emperor
# Auto-converted from Orbs timers

[[boss]]
id = "prototype_a_14_prototype_b_16"
name = "Prototype A-14 & Prototype B-16"
area_name = "The False Emperor"
difficulties = ["master", "veteran"]
npc_names = ["Prototype A-14 & Prototype B-16"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "prototype_a_14_prototype_b_16_swap_a_14"
name = "Swap A-14"
trigger = { type = "effect_applied", effect_ids = [1790223973351685] }
duration_secs = 30.0
color = [220, 39, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prototype_a_14_prototype_b_16_swap_b_16"
name = "Swap B-16"
trigger = { type = "effect_applied", effect_ids = [1790223973351685] }
duration_secs = 30.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]
