# Sith Entity - The False Emperor
# Auto-converted from Orbs timers

[[boss]]
id = "sith_entity"
name = "Sith Entity"
area_name = "The False Emperor"
difficulties = ["master", "veteran"]
npc_names = ["Sith Entity"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "sith_entity_affliction_1st"
name = "Affliction 1st"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [12, 136, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_knocback_1st"
name = "Knocback 1st"
trigger = { type = "timer_expires", timer_id = "sith_entity_affliction_1st" }
duration_secs = 5.0
color = [43, 40, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_force_lightning_1st"
name = "Force Lightning 1st"
trigger = { type = "timer_expires", timer_id = "sith_entity_knocback_1st" }
duration_secs = 5.0
color = [119, 27, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 300.0
color = [228, 38, 34, 255]
difficulties = ["master"]

[[boss.timer]]
id = "sith_entity_mass_lightning"
name = "Mass Lightning"
trigger = { type = "ability_cast", ability_ids = [2158289785716736] }
duration_secs = 30.0
color = [243, 103, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_affliction"
name = "Affliction"
trigger = { type = "ability_cast", ability_ids = [2157117259644928] }
duration_secs = 10.0
color = [20, 167, 46, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [2157121554612224] }
duration_secs = 30.0
color = [35, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_force_lightning"
name = "Force Lightning"
trigger = { type = "ability_cast", ability_ids = [2157228928794624] }
duration_secs = 20.0
color = [128, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_knockback_a"
name = "Knockback A"
trigger = { type = "timer_expires", timer_id = "c253d7aa-d4a2-4831-adbd-7cfd3d77e327" }
duration_secs = 5.0
color = [35, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "sith_entity_force_lightning_a"
name = "Force Lightning A"
trigger = { type = "timer_expires", timer_id = "sith_entity_knockback_a" }
duration_secs = 5.0
color = [127, 32, 220, 255]
difficulties = ["veteran", "master"]
