# Dread Master Tyrans - The Dread Palace
# Auto-converted from Orbs timers

[[boss]]
id = "dread_master_tyrans"
name = "Dread Master Tyrans"
area_name = "The Dread Palace"
difficulties = ["master", "veteran"]
npc_names = ["Dread Master Tyrans"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "dread_master_tyrans_simplification"
name = "Simplification"
trigger = { type = "ability_cast", ability_ids = [3298934315286528] }
duration_secs = 24.0
color = [224, 29, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_tyrans_inferno"
name = "Inferno"
trigger = { type = "ability_cast", ability_ids = [3277841730895872] }
duration_secs = 19.0
color = [219, 113, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_tyrans_nim_inferno"
name = "Nim Inferno"
trigger = { type = "ability_cast", ability_ids = [3349606339444736] }
duration_secs = 19.0
color = [219, 113, 28, 255]
difficulties = ["veteran", "master"]
