# Syndic Zenta - A Traitor Among The Chiss
# Auto-converted from Orbs timers

[[boss]]
id = "syndic_zenta"
name = "Syndic Zenta"
area_name = "A Traitor Among The Chiss"
difficulties = ["master", "veteran"]
npc_names = ["Syndic Zenta"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "syndic_zenta_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [4138836644855808] }
duration_secs = 20.0
color = [217, 26, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_magnetic_charge"
name = "Magnetic Charge"
trigger = { type = "ability_cast", ability_ids = [4136714931011584] }
duration_secs = 11.5
color = [220, 32, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_medic"
name = "Medic"
trigger = { type = "ability_cast", ability_ids = [4137170197544960] }
duration_secs = 60.0
color = [220, 212, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_laser_droid"
name = "Laser Droid"
trigger = { type = "ability_cast", ability_ids = [4136379923562496] }
duration_secs = 60.0
color = [112, 197, 17, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_assassins"
name = "Assassins"
trigger = { type = "ability_cast", ability_ids = [4136414283300864] }
duration_secs = 60.0
color = [7, 128, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [4151811741057024] }
duration_secs = 14.0
color = [228, 116, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_snipe"
name = "Snipe"
trigger = { type = "ability_cast", ability_ids = [4140116545110016] }
duration_secs = 11.0
color = [213, 30, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_snipers"
name = "Snipers"
trigger = { type = "ability_cast", ability_ids = [4136375628595200] }
duration_secs = 60.0
color = [13, 121, 11, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_static_probe"
name = "Static Probe"
trigger = { type = "ability_cast", ability_ids = [4145493844164608] }
duration_secs = 33.0
color = [220, 31, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_assassins_2"
name = "Assassins_"
trigger = { type = "ability_cast", ability_ids = [4140193854521344] }
duration_secs = 40.0
color = [13, 113, 14, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_tank_droids"
name = "Tank Droids"
trigger = { type = "ability_cast", ability_ids = [4136384218529792] }
duration_secs = 60.0
color = [115, 220, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "syndic_zenta_demo_droid"
name = "Demo Droid"
trigger = { type = "ability_cast", ability_ids = [4149479573815296] }
duration_secs = 40.0
color = [202, 213, 31, 255]
difficulties = ["veteran", "master"]
