# Valss - A Traitor Among The Chiss
# Auto-converted from Orbs timers

[[boss]]
id = "valss"
name = "Valss"
area_name = "A Traitor Among The Chiss"
difficulties = ["master", "veteran"]
npc_names = ["Valss"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "valss_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [4134623281938432] }
duration_secs = 15.0
color = [228, 39, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_bombardment"
name = "Bombardment_"
trigger = { type = "ability_cast", ability_ids = [4136263959445504] }
duration_secs = 30.0
color = [228, 128, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_bombardment_2"
name = "Bombardment"
trigger = { type = "ability_cast", ability_ids = [4134812260499456] }
duration_secs = 39.0
color = [228, 124, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_impulse_2"
name = "Impulse_"
trigger = { type = "ability_cast", ability_ids = [4135396376051712] }
duration_secs = 30.0
color = [220, 26, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_powered_shot"
name = "Powered Shot"
trigger = { type = "ability_cast", ability_ids = [4134503022854144] }
duration_secs = 30.0
color = [220, 26, 205, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_master_stroke"
name = "Master Stroke"
trigger = { type = "ability_cast", ability_ids = [4135435030757376] }
duration_secs = 25.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_mine_primer"
name = "Mine primer"
trigger = { type = "ability_cast", ability_ids = [4147375039840256] }
duration_secs = 79.0
color = [197, 213, 38, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "valss_blizzard_burst"
name = "Blizzard Burst"
trigger = { type = "ability_cast", ability_ids = [4147581198270464] }
duration_secs = 30.0
color = [27, 228, 218, 255]
difficulties = ["veteran", "master"]
