# Graul - Secrets of the Enclave
# Auto-converted from Orbs timers

[[boss]]
id = "graul"
name = "Graul"
area_name = "Secrets of the Enclave"
difficulties = ["master", "veteran"]
npc_names = ["Graul"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "graul_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4447455814877184] }
duration_secs = 30.0
color = [12, 136, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "graul_slam"
name = "Slam"
trigger = { type = "ability_cast", ability_ids = [4450183119110144] }
duration_secs = 15.0
color = [213, 30, 25, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "graul_quaking_blows_mm"
name = "Quaking Blows MM"
trigger = { type = "ability_cast", ability_ids = [4456380756918272] }
duration_secs = 30.0
color = [228, 98, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "graul_quaking_blows"
name = "Quaking Blows"
trigger = { type = "ability_cast", ability_ids = [4447460109844480] }
duration_secs = 30.0
color = [228, 217, 34, 255]
difficulties = ["veteran", "master"]
