# Master Leeha Narezz - Secrets of the Enclave
# Auto-converted from Orbs timers

[[boss]]
id = "master_leeha_narezz"
name = "Master Leeha Narezz"
area_name = "Secrets of the Enclave"
difficulties = ["master", "veteran"]
npc_names = ["Master Leeha Narezz"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "master_leeha_narezz_center_jump"
name = "Center Jump"
trigger = { type = "ability_cast", ability_ids = [4448658405720064] }
duration_secs = 15.0
color = [211, 213, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_leeha_narezz_forcequake"
name = "Forcequake"
trigger = { type = "ability_cast", ability_ids = [4451158076686336] }
duration_secs = 45.0
color = [220, 41, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_leeha_narezz_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [4458154578411520] }
duration_secs = 23.0
color = [213, 117, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "master_leeha_narezz_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4448714240294912] }
duration_secs = 16.0
color = [14, 121, 22, 255]
difficulties = ["veteran", "master"]
