# Goldie - Spirit of Vengeance
# Auto-converted from Orbs timers

[[boss]]
id = "goldie"
name = "Goldie"
area_name = "Spirit of Vengeance"
difficulties = ["master", "veteran"]
npc_names = ["Goldie"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "goldie_slam"
name = "Slam"
trigger = { type = "ability_cast", ability_ids = [4439110693421056] }
duration_secs = 33.0
color = [213, 34, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "goldie_swipe"
name = "Swipe"
trigger = { type = "ability_cast", ability_ids = [4439097808519168] }
duration_secs = 8.0
color = [31, 195, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "goldie_swipe_2"
name = "Swipe_"
trigger = { type = "ability_cast", ability_ids = [4439102103486464] }
duration_secs = 10.0
color = [39, 217, 220, 255]
difficulties = ["veteran", "master"]
