# Heta Kol - Spirit of Vengeance
# Auto-converted from Orbs timers

[[boss]]
id = "heta_kol"
name = "Heta Kol"
area_name = "Spirit of Vengeance"
difficulties = ["master", "veteran"]
npc_names = ["Heta Kol"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "heta_kol_flamethrower"
name = "Flamethrower"
trigger = { type = "ability_cast", ability_ids = [4438419203686400] }
duration_secs = 15.0
color = [228, 139, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "heta_kol_grenade"
name = "Grenade"
trigger = { type = "ability_cast", ability_ids = [4438024066695168] }
duration_secs = 9.0
color = [220, 31, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "heta_kol_lockdown"
name = "Lockdown"
trigger = { type = "ability_cast", ability_ids = [4437001864478720] }
duration_secs = 30.0
color = [220, 39, 196, 255]
difficulties = ["veteran", "master"]
