# DN-314 Tunneler - Hammer Station
# Auto-converted from Orbs timers

[[boss]]
id = "dn_314_tunneler"
name = "DN-314 Tunneler"
area_name = "Hammer Station"
difficulties = ["master", "veteran"]
npc_names = ["DN-314 Tunneler"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "dn_314_tunneler_targeted_laser"
name = "Targeted Laser"
trigger = { type = "ability_cast", ability_ids = [3169647209742336] }
duration_secs = 21.0
color = [228, 121, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dn_314_tunneler_adds_1"
name = "Adds 1"
trigger = { type = "ability_cast", ability_ids = [3163939198205952] }
duration_secs = 10.0
color = [20, 174, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dn_314_tunneler_adds_2"
name = "Adds 2"
trigger = { type = "timer_expires", timer_id = "dn_314_tunneler_adds_1" }
duration_secs = 10.0
color = [16, 182, 42, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dn_314_tunneler_adds_3"
name = "Adds 3"
trigger = { type = "timer_expires", timer_id = "dn_314_tunneler_adds_2" }
duration_secs = 10.0
color = [20, 174, 46, 255]
difficulties = ["veteran", "master"]
