# Vorgan the Volcano - Hammer Station
# Auto-converted from Orbs timers

[[boss]]
id = "vorgan_the_volcano"
name = "Vorgan the Volcano"
area_name = "Hammer Station"
difficulties = ["master"]
npc_names = ["Vorgan the Volcano"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "vorgan_the_volcano_shield_1st"
name = "Shield 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [27, 228, 223, 255]
difficulties = ["master"]

[[boss.timer]]
id = "vorgan_the_volcano_shield_self"
name = "Shield Self"
trigger = { type = "ability_cast", ability_ids = [3230060219727872] }
duration_secs = 45.0
color = [32, 220, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "vorgan_the_volcano_shielf_friends"
name = "Shielf Friends"
trigger = { type = "ability_cast", ability_ids = [3230068809662464] }
duration_secs = 60.0
color = [28, 20, 228, 255]
difficulties = ["master"]

[[boss.timer]]
id = "vorgan_the_volcano_shield_active"
name = "Shield Active"
trigger = { type = "ability_cast", ability_ids = [3230060219727872] }
duration_secs = 20.0
color = [220, 39, 32, 255]
difficulties = ["master"]
