# Commander Mokan - Battle of Rishi
# Auto-converted from Orbs timers

[[boss]]
id = "commander_mokan"
name = "Commander Mokan"
area_name = "Battle of Rishi"
difficulties = ["master", "veteran"]
npc_names = ["Commander Mokan"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_mokan_compound_17"
name = "Compound 17_"
trigger = { type = "combat_start" }
duration_secs = 35.0
color = [213, 32, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_mokan_compound_17_2"
name = "Compound 17"
trigger = { type = "ability_cast", ability_ids = [3535548358590464] }
duration_secs = 43.0
color = [220, 42, 32, 255]
difficulties = ["veteran", "master"]
