# Shield Squadron Unit 1 - Battle of Rishi
# Auto-converted from Orbs timers

[[boss]]
id = "shield_squadron_unit_1"
name = "Shield Squadron Unit 1"
area_name = "Battle of Rishi"
difficulties = ["master", "veteran"]
npc_names = ["Shield Squadron Unit 1"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "shield_squadron_unit_1_electrical_megastorm"
name = "Electrical Megastorm"
trigger = { type = "ability_cast", ability_ids = [3393835912658944] }
duration_secs = 90.0
color = [32, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_missile_setup"
name = "Missile Setup"
trigger = { type = "ability_cast", ability_ids = [3398719290474496] }
duration_secs = 18.0
color = [220, 37, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_missile_blast"
name = "Missile Blast"
trigger = { type = "timer_expires", timer_id = "shield_squadron_unit_1_missile_setup" }
duration_secs = 22.0
color = [228, 34, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_missile_blast_2"
name = "Missile Blast_"
trigger = { type = "ability_cast", ability_ids = [3395214597160960] }
duration_secs = 22.0
color = [220, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_adds_setup"
name = "Adds Setup"
trigger = { type = "ability_cast", ability_ids = [3395214597160960] }
duration_secs = 62.0
color = [18, 136, 16, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_adds"
name = "Adds"
trigger = { type = "timer_expires", timer_id = "shield_squadron_unit_1_adds_setup" }
duration_secs = 20.0
color = [21, 128, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_adds_2"
name = "Adds_"
trigger = { type = "ability_cast", ability_ids = [3398719290474496] }
duration_secs = 20.0
color = [15, 128, 17, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "shield_squadron_unit_1_orbital_multistrike"
name = "Orbital Multistrike"
trigger = { type = "ability_cast", ability_ids = [3535453869309952] }
duration_secs = 36.0
color = [220, 98, 32, 255]
difficulties = ["veteran", "master"]
