# Ortuno - Depths of Manaan
# Auto-converted from Orbs timers

[[boss]]
id = "ortuno"
name = "Ortuno"
area_name = "Depths of Manaan"
difficulties = ["master", "veteran"]
npc_names = ["Ortuno"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "ortuno_immune"
name = "Immune"
trigger = { type = "ability_cast", ability_ids = [3361408909574144] }
duration_secs = 13.0
color = [228, 40, 45, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "ortuno_flow_erruption"
name = "Flow + Erruption"
trigger = { type = "timer_expires", timer_id = "ortuno_immune" }
duration_secs = 38.0
color = [220, 21, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "ortuno_water"
name = "Water_"
trigger = { type = "ability_cast", ability_ids = [3361645132775424] }
duration_secs = 6.8
color = [27, 49, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "ortuno_mass_water"
name = "Mass Water"
trigger = { type = "ability_cast", ability_ids = [3505891609411584] }
duration_secs = 48.8
color = [27, 228, 218, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "ortuno_mass_water_flow"
name = "Mass Water + Flow"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]
