# LR-5 Sentinel Droid - Lost Island
# Auto-converted from Orbs timers

[[boss]]
id = "lr_5_sentinel_droid"
name = "LR-5 Sentinel Droid"
area_name = "Lost Island"
difficulties = ["master", "veteran"]
npc_names = ["LR-5 Sentinel Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "lr_5_sentinel_droid_incinerate"
name = "Incinerate"
trigger = { type = "ability_cast", ability_ids = [2851183974678528] }
duration_secs = 17.5
color = [220, 113, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 255.0
color = [220, 37, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_discharge_1st"
name = "Discharge 1st"
trigger = { type = "combat_start" }
duration_secs = 19.0
color = [32, 204, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_discharge"
name = "Discharge_"
trigger = { type = "timer_expires", timer_id = "lr_5_sentinel_droid_discharge_2" }
duration_secs = 20.0
color = [32, 208, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "lr_5_sentinel_droid_discharge_2"
name = "Discharge"
trigger = { type = "timer_expires", timer_id = "lr_5_sentinel_droid_discharge_1st" }
duration_secs = 20.0
color = [38, 213, 212, 255]
difficulties = ["veteran", "master"]
