# Project Sav-Rak - Lost Island
# Auto-converted from Orbs timers

[[boss]]
id = "project_sav_rak"
name = "Project Sav-Rak"
area_name = "Lost Island"
difficulties = ["master", "veteran"]
npc_names = ["Project Sav-Rak"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "project_sav_rak_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 280.0
color = [220, 33, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "project_sav_rak_smash"
name = "Smash"
trigger = { type = "ability_cast", ability_ids = [2837543158546432] }
duration_secs = 24.0
color = [220, 104, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "project_sav_rak_smash_2"
name = "Smash_"
trigger = { type = "combat_start" }
duration_secs = 12.0
color = [220, 97, 32, 255]
difficulties = ["veteran", "master"]
