# NAHUT - The Gods from the Machine
# Auto-converted from Orbs timers

[[boss]]
id = "nahut"
name = "NAHUT"
area_name = "The Gods from the Machine"
difficulties = ["master"]
npc_names = ["NAHUT"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "nahut_discharge_1st"
name = "Discharge 1st"
trigger = { type = "ability_cast", ability_ids = [4133906022400000] }
duration_secs = 12.0
color = [23, 37, 232, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_slice"
name = "Slice"
trigger = { type = "ability_cast", ability_ids = [4137075708264448] }
duration_secs = 12.0
color = [208, 16, 17, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_suppression"
name = "Suppression"
trigger = { type = "ability_cast", ability_ids = [4181850742325248] }
duration_secs = 16.0
color = [227, 106, 31, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_mass_distortion_p1"
name = "Mass Distortion P1"
trigger = { type = "ability_cast", ability_ids = [4126462844076032] }
duration_secs = 11.0
color = [153, 27, 227, 255]
phases = ["p1"]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_turret_spawn"
name = "Turret Spawn"
trigger = { type = "ability_cast", ability_ids = [4134120770764800] }
duration_secs = 40.0
color = [102, 71, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_turrets_1st"
name = "Turrets 1st"
trigger = { type = "effect_removed", effect_ids = [4134133655667051] }
duration_secs = 10.0
color = [102, 71, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_suppression_cd"
name = "Suppression CD"
trigger = { type = "ability_cast", ability_ids = [4181850742325248] }
duration_secs = 60.5
color = [204, 192, 46, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_mass_distortion"
name = "Mass Distortion"
trigger = { type = "ability_cast", ability_ids = [4124212281212928] }
duration_secs = 12.5
color = [142, 30, 222, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nahut_mass_distortion_p3"
name = "Mass Distortion P3"
trigger = { type = "effect_removed", effect_ids = [4134133655667051] }
duration_secs = 12.0
color = [154, 30, 222, 255]
phases = ["p3"]
difficulties = ["master"]
