# TYTH - The Gods from the Machine
# Auto-converted from Orbs timers

[[boss]]
id = "tyth"
name = "TYTH"
area_name = "The Gods from the Machine"
difficulties = ["master"]
npc_names = ["TYTH"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "tyth_adds_setup"
name = "Adds setup"
trigger = { type = "timer_expires", timer_id = "tyth_adds" }
duration_secs = 17.0
color = [54, 214, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4076168777039872] }
duration_secs = 15.0
color = [54, 214, 32, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_inversion_1st"
name = "Inversion 1st"
trigger = { type = "combat_start" }
duration_secs = 21.0
color = [184, 29, 224, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_inversion"
name = "Inversion"
trigger = { type = "ability_cast", ability_ids = [4071117895499776] }
duration_secs = 37.0
color = [184, 29, 224, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_energy_wave"
name = "Energy Wave"
trigger = { type = "ability_cast", ability_ids = [4081339917664256] }
duration_secs = 12.0
color = [224, 29, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "tyth_sweep"
name = "Sweep"
trigger = { type = "ability_cast", ability_ids = [4080279060742144] }
duration_secs = 6.0
color = [214, 108, 32, 255]
difficulties = ["master"]
