# Revanite Commanders - Temple of Sacrifice
# Auto-converted from Orbs timers

[[boss]]
id = "revanite_commanders"
name = "Revanite Commanders"
area_name = "Temple of Sacrifice"
difficulties = ["master", "veteran"]
npc_names = ["Revanite Commanders"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "revanite_commanders_volley_knock_tp"
name = "Volley/Knock/TP"
trigger = { type = "ability_cast", ability_ids = [3473331462340608] }
duration_secs = 10.0
color = [219, 110, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "revanite_commanders_kurse_smash"
name = "Kurse Smash"
trigger = { type = "ability_cast", ability_ids = [3471978547642368] }
duration_secs = 18.0
color = [40, 32, 214, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "revanite_commanders_deron_teleport"
name = "Deron Teleport"
trigger = { type = "ability_cast", ability_ids = [3472622792736768] }
duration_secs = 15.0
color = [37, 219, 218, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "revanite_commanders_deron_knockback"
name = "Deron Knockback"
trigger = { type = "ability_cast", ability_ids = [3472695807180800] }
duration_secs = 24.0
color = [219, 32, 35, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "revanite_commanders_deron_volley"
name = "Deron Volley"
trigger = { type = "ability_cast", ability_ids = [3473494671097856] }
duration_secs = 21.0
color = [219, 117, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "revanite_commanders_sano_kick"
name = "Sano Kick"
trigger = { type = "ability_cast", ability_ids = [3477248472514560] }
duration_secs = 15.0
color = [179, 175, 23, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "revanite_commanders_sano_kick_2"
name = "Sano Kick_"
trigger = { type = "ability_cast", ability_ids = [3461713575804928] }
duration_secs = 14.0
color = [179, 175, 23, 255]
difficulties = ["veteran", "master"]
