# Bonethrasher - Karagga's Palace
# Auto-converted from Orbs timers

[[boss]]
id = "bonethrasher"
name = "Bonethrasher"
area_name = "Karagga's Palace"
difficulties = ["master", "veteran"]
npc_names = ["Bonethrasher"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "bonethrasher_super_smash_1st"
name = "Super Smash 1st"
trigger = { type = "timer_expires", timer_id = "81d3ba6b-e952-4273-b0ff-28e1d0d949e9" }
duration_secs = 10.0
color = [39, 220, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bonethrasher_smash_1st"
name = "Smash 1st"
trigger = { type = "timer_expires", timer_id = "bonethrasher_super_smash_1st" }
duration_secs = 10.0
color = [220, 26, 180, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bonethrasher_sweep_cs"
name = "Sweep CS"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [224, 103, 29, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_super_smash_cs"
name = "Super Smash CS"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [29, 224, 221, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_smash_cs"
name = "Smash CS"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [224, 24, 212, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_about_to_eat"
name = "About to Eat"
trigger = { type = "timer_expires", timer_id = "bonethrasher_gammorean" }
duration_secs = 10.0
color = [190, 178, 34, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "bonethrasher_gammorean"
name = "Gammorean"
trigger = { type = "ability_cast", ability_ids = [2068658113216512] }
duration_secs = 10.0
color = [190, 178, 34, 255]
difficulties = ["veteran"]
