# Jarg & Sorno - Karagga's Palace
# Auto-converted from Orbs timers

[[boss]]
id = "jarg_sorno"
name = "Jarg & Sorno"
area_name = "Karagga's Palace"
difficulties = ["veteran"]
npc_names = ["Jarg & Sorno"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "jarg_sorno_sorno_back"
name = "Sorno back"
trigger = { type = "ability_cast", ability_ids = [2759280264478720] }
duration_secs = 30.0
color = [219, 24, 24, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "jarg_sorno_thermal_detonator"
name = "Thermal Detonator_"
trigger = { type = "ability_cast", ability_ids = [2759284559446016] }
duration_secs = 16.0
color = [224, 33, 35, 255]
difficulties = ["veteran"]
