# Karagga the Unyielding - Karagga's Palace
# Auto-converted from Orbs timers

[[boss]]
id = "karagga_the_unyielding"
name = "Karagga the Unyielding"
area_name = "Karagga's Palace"
difficulties = ["veteran"]
npc_names = ["Karagga the Unyielding"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "karagga_the_unyielding_cluster_bombs_1st"
name = "Cluster Bombs 1st"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [204, 195, 46, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_unstable_energy_1st"
name = "Unstable Energy 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [186, 29, 224, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_burning_oil_1st"
name = "Burning Oil 1st"
trigger = { type = "combat_start" }
duration_secs = 20.0
color = [123, 86, 42, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_tunneling_drill_1st"
name = "Tunneling Drill 1st"
trigger = { type = "combat_start" }
duration_secs = 25.0
color = [224, 29, 29, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_mouse_droids"
name = "Mouse Droids"
trigger = { type = "ability_cast", ability_ids = [2778268314894336] }
duration_secs = 60.0
color = [61, 143, 61, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "karagga_the_unyielding_mouse_droids_1st"
name = "Mouse Droids 1st"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [61, 143, 61, 255]
difficulties = ["veteran"]
