# GXR-7 Command Droid - The Black Talon
# Auto-converted from Orbs timers

[[boss]]
id = "gxr_7_command_droid"
name = "GXR-7 Command Droid"
area_name = "The Black Talon"
difficulties = ["master", "veteran"]
npc_names = ["GXR-7 Command Droid"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gxr_7_command_droid_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 90.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gxr_7_command_droid_power_punch"
name = "Power Punch"
trigger = { type = "ability_cast", ability_ids = [2517117123428352] }
duration_secs = 20.0
color = [205, 106, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gxr_7_command_droid_power_blast"
name = "Power Blast"
trigger = { type = "ability_cast", ability_ids = [2517112828461056] }
duration_secs = 12.0
color = [224, 228, 27, 255]
difficulties = ["veteran", "master"]
