# Yadira Ban - The Black Talon
# Auto-converted from Orbs timers

[[boss]]
id = "yadira_ban"
name = "Yadira Ban"
area_name = "The Black Talon"
difficulties = ["master", "veteran"]
npc_names = ["Yadira Ban"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "yadira_ban_force_charge"
name = "Force Charge"
trigger = { type = "ability_cast", ability_ids = [2031970502574080] }
duration_secs = 9.0
color = [225, 65, 243, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "yadira_ban_cyclone_nova"
name = "Cyclone Nova"
trigger = { type = "ability_cast", ability_ids = [850738532057088] }
duration_secs = 19.5
color = [39, 220, 214, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "yadira_ban_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 70.0
color = [228, 40, 43, 255]
difficulties = ["master"]
