# Olok the Shadow - Scum and Villainy
# Auto-converted from Orbs timers

[[boss]]
id = "olok_the_shadow"
name = "Olok the Shadow"
area_name = "Scum and Villainy"
difficulties = ["master", "veteran"]
npc_names = ["Olok the Shadow"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "olok_the_shadow_stealthed"
name = "Stealthed"
trigger = { type = "ability_cast", ability_ids = [3132057655967744] }
duration_secs = 5.5
color = [29, 224, 221, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "olok_the_shadow_flashbang"
name = "Flashbang_"
trigger = { type = "ability_cast", ability_ids = [3131215842377728] }
duration_secs = 40.0
color = [219, 187, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "olok_the_shadow_stealth"
name = "Stealth"
trigger = { type = "ability_cast", ability_ids = [3131215842377728] }
duration_secs = 4.5
color = [29, 224, 221, 255]
difficulties = ["veteran", "master"]
