# Operations Chief - Scum and Villainy
# Auto-converted from Orbs timers

[[boss]]
id = "operations_chief"
name = "Operations Chief"
area_name = "Scum and Villainy"
difficulties = ["master", "veteran"]
npc_names = ["Operations Chief"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "operations_chief_flash_bang"
name = "Flash Bang"
trigger = { type = "ability_cast", ability_ids = [3146325537325056] }
duration_secs = 30.0
color = [184, 183, 49, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "operations_chief_terminate"
name = "Terminate"
trigger = { type = "ability_cast", ability_ids = [3146334127259648] }
duration_secs = 24.0
color = [224, 28, 24, 255]
difficulties = ["master"]

[[boss.timer]]
id = "operations_chief_explosive_probe"
name = "Explosive Probe"
trigger = { type = "ability_cast", ability_ids = [3146329832292352] }
duration_secs = 32.0
color = [224, 88, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "operations_chief_turrets"
name = "Turrets"
trigger = { type = "ability_cast", ability_ids = [3158012143337472] }
duration_secs = 32.0
color = [214, 32, 206, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "operations_chief_impulse"
name = "Impulse"
trigger = { type = "ability_cast", ability_ids = [2166591957499904] }
duration_secs = 15.0
color = [37, 29, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "operations_chief_thermal_grenade"
name = "Thermal Grenade"
trigger = { type = "ability_cast", ability_ids = [3145707062034432] }
duration_secs = 20.0
color = [12, 133, 17, 255]
difficulties = ["veteran", "master"]
