# Kirba, the Forgotten - Shrine of Silence
# Auto-converted from Orbs timers

[[boss]]
id = "kirba_the_forgotten"
name = "Kirba, the Forgotten"
area_name = "Shrine of Silence"
difficulties = ["master", "veteran"]
npc_names = ["Kirba, the Forgotten"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "kirba_the_forgotten_blast_of_hatred"
name = "Blast of Hatred"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [128, 32, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_forceful_presence"
name = "Forceful Presence"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_blast_of_hatred" }
duration_secs = 10.0
color = [39, 220, 211, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_furious_bellow"
name = "Furious Bellow"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_forceful_presence" }
duration_secs = 10.0
color = [213, 117, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_enraged_stomp"
name = "Enraged Stomp"
trigger = { type = "ability_cast", ability_ids = [4677219385344000] }
duration_secs = 12.0
color = [228, 44, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_ancient_s_rage"
name = "Ancient's Rage"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_furious_bellow" }
duration_secs = 5.0
color = [220, 218, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_ancient_s_rage_2"
name = "Ancient's Rage_"
trigger = { type = "ability_cast", ability_ids = [4677709011615744] }
duration_secs = 61.0
color = [220, 217, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_forceful_presence_2"
name = "Forceful Presence_"
trigger = { type = "ability_cast", ability_ids = [4676824248352768] }
duration_secs = 15.0
color = [25, 213, 208, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_furious_bellow_2"
name = "Furious Bellow_"
trigger = { type = "ability_cast", ability_ids = [4677077651423232] }
duration_secs = 23.0
color = [228, 133, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_resist"
name = "Resist"
trigger = { type = "ability_cast", ability_ids = [4677064766521344] }
duration_secs = 4.3
color = [124, 32, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kirba_the_forgotten_blast_of_hatred_2"
name = "Blast of Hatred_"
trigger = { type = "timer_expires", timer_id = "kirba_the_forgotten_resist" }
duration_secs = 15.7
color = [131, 26, 220, 255]
difficulties = ["veteran", "master"]
