# GEMINI 16 - The Nathema Conspiracy
# Auto-converted from Orbs timers

[[boss]]
id = "gemini_16"
name = "GEMINI 16"
area_name = "The Nathema Conspiracy"
difficulties = ["master", "veteran"]
npc_names = ["GEMINI 16"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gemini_16_beam"
name = "Beam"
trigger = { type = "ability_cast", ability_ids = [4163472577265664] }
duration_secs = 17.0
color = [220, 39, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gemini_16_adds_vm"
name = "Adds VM"
trigger = { type = "ability_cast", ability_ids = [4162446080081920] }
duration_secs = 45.0
color = [32, 213, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "gemini_16_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4162235626684416] }
duration_secs = 30.0
color = [21, 144, 27, 255]
difficulties = ["veteran", "master"]
