# Vinn Atrius & Zildrog - The Nathema Conspiracy
# Auto-converted from Orbs timers

[[boss]]
id = "vinn_atrius_zildrog"
name = "Vinn Atrius & Zildrog"
area_name = "The Nathema Conspiracy"
difficulties = ["master", "veteran"]
npc_names = ["Vinn Atrius & Zildrog"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "vinn_atrius_zildrog_lifeforce_shackle_1st"
name = "Lifeforce Shackle 1st"
trigger = { type = "combat_start" }
duration_secs = 19.0
color = [220, 59, 150, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_force_blast_1st"
name = "Force Blast 1st"
trigger = { type = "combat_start" }
duration_secs = 9.0
color = [179, 182, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_lifeforce_shackle"
name = "Lifeforce Shackle"
trigger = { type = "effect_applied", effect_ids = [4159297869054208] }
duration_secs = 17.0
color = [213, 51, 152, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_rupture"
name = "Rupture"
trigger = { type = "ability_cast", ability_ids = [4160706618327040] }
duration_secs = 20.0
color = [220, 114, 19, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_lightning_storm"
name = "Lightning Storm"
trigger = { type = "ability_cast", ability_ids = [4160693733425152] }
duration_secs = 20.0
color = [34, 50, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_horizon_lance"
name = "Horizon Lance"
trigger = { type = "ability_cast", ability_ids = [4166221356335104] }
duration_secs = 17.0
color = [155, 61, 255, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_surging_strike"
name = "Surging Strike"
trigger = { type = "ability_cast", ability_ids = [4158975746506752] }
duration_secs = 20.0
color = [148, 77, 236, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_force_blast"
name = "Force Blast"
trigger = { type = "ability_cast", ability_ids = [4160685143490560] }
duration_secs = 17.0
color = [190, 190, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_breath_of_izax"
name = "Breath of Izax"
trigger = { type = "ability_cast", ability_ids = [4168261465800704] }
duration_secs = 30.0
color = [31, 199, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "vinn_atrius_zildrog_lifeforce_shackle_2"
name = "Lifeforce Shackle_"
trigger = { type = "effect_applied", effect_ids = [4180033971159344] }
duration_secs = 17.0
color = [228, 34, 172, 255]
difficulties = ["veteran", "master"]
