# Voreclaw - The Nathema Conspiracy
# Auto-converted from Orbs timers

[[boss]]
id = "voreclaw"
name = "Voreclaw"
area_name = "The Nathema Conspiracy"
difficulties = ["master", "veteran"]
npc_names = ["Voreclaw"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "voreclaw_power_leap"
name = "Power Leap"
trigger = { type = "ability_cast", ability_ids = [4152992857063424] }
duration_secs = 17.0
color = [205, 26, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voreclaw_burrow"
name = "Burrow"
trigger = { type = "ability_cast", ability_ids = [4157631421743104] }
duration_secs = 30.0
color = [220, 122, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "voreclaw_burrowed"
name = "Burrowed"
trigger = { type = "ability_cast", ability_ids = [4157631421743104] }
duration_secs = 15.0
color = [220, 39, 41, 255]
difficulties = ["veteran", "master"]
