# Propagator Core XR-53 - Propagator Core
# Auto-converted from Orbs timers

[[boss]]
id = "propagator_core_xr_53"
name = "Propagator Core XR-53"
area_name = "Propagator Core"
difficulties = ["master", "story", "veteran"]
npc_names = ["Propagator Core XR-53"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "propagator_core_xr_53_lethal_strike"
name = "Lethal Strike"
trigger = { type = "ability_cast", ability_ids = [4826160261234688] }
duration_secs = 30.0
color = [237, 33, 33, 255]
difficulties = ["story", "veteran", "master"]

[[boss.timer]]
id = "propagator_core_xr_53_acidic_rocketry"
name = "Acidic Rocketry"
trigger = { type = "ability_cast", ability_ids = [4827160988614656] }
duration_secs = 20.0
color = [23, 152, 0, 255]
difficulties = ["story", "veteran", "master"]

[[boss.timer]]
id = "propagator_core_xr_53_cleanse_flood_add"
name = "Cleanse Flood Add"
trigger = { type = "ability_cast", ability_ids = [4832241934925824] }
duration_secs = 90.0
color = [51, 200, 237, 255]
difficulties = ["story", "veteran", "master"]

[[boss.timer]]
id = "propagator_core_xr_53_extraneous_expulsion"
name = "Extraneous Expulsion"
trigger = { type = "ability_cast", ability_ids = [4825717879603200] }
duration_secs = 25.0
color = [182, 237, 40, 255]
difficulties = ["story", "veteran", "master"]

[[boss.timer]]
id = "propagator_core_xr_53_hunting_grounds"
name = "Hunting Grounds"
trigger = { type = "ability_cast", ability_ids = [4828045751877632] }
duration_secs = 30.0
color = [237, 165, 0, 255]
difficulties = ["story", "veteran", "master"]

[[boss.timer]]
id = "propagator_core_xr_53_hungering_bite"
name = "Hungering Bite"
trigger = { type = "ability_cast", ability_ids = [4825876793393152] }
duration_secs = 22.5
color = [237, 23, 93, 255]
difficulties = ["story", "veteran", "master"]
