# Prophet of Vodal - Athiss
# Auto-converted from Orbs timers

[[boss]]
id = "prophet_of_vodal"
name = "Prophet of Vodal"
area_name = "Athiss"
difficulties = ["master", "veteran"]
npc_names = ["Prophet of Vodal"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "prophet_of_vodal_corruption"
name = "Corruption"
trigger = { type = "ability_cast", ability_ids = [2278832337846272] }
duration_secs = 21.5
color = [19, 159, 35, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_affliction"
name = "Affliction"
trigger = { type = "ability_cast", ability_ids = [2276813703217152] }
duration_secs = 16.0
color = [151, 205, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_corruption_2"
name = "Corruption_"
trigger = { type = "ability_cast", ability_ids = [3229106736988160] }
duration_secs = 30.0
color = [16, 136, 23, 255]
difficulties = ["master"]

[[boss.timer]]
id = "prophet_of_vodal_adds_immunity"
name = "Adds Immunity"
trigger = { type = "effect_applied", effect_ids = [2279489467842560] }
duration_secs = 110.0
color = [26, 216, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_lightning"
name = "Lightning"
trigger = { type = "ability_cast", ability_ids = [2277586797330432] }
duration_secs = 30.0
color = [228, 34, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_affliction_2"
name = "Affliction_"
trigger = { type = "timer_expires", timer_id = "prophet_of_vodal_corruption" }
duration_secs = 10.0
color = [142, 190, 22, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "prophet_of_vodal_lightning_affliction"
name = "Lightning + Affliction"
trigger = { type = "timer_expires", timer_id = "prophet_of_vodal_corruption" }
duration_secs = 10.0
color = [220, 28, 26, 255]
difficulties = ["veteran", "master"]
