# Corruptor Zero - The Dread Fortress
# Auto-converted from Orbs timers

[[boss]]
id = "corruptor_zero"
name = "Corruptor Zero"
area_name = "The Dread Fortress"
difficulties = ["master", "veteran"]
npc_names = ["Corruptor Zero"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "corruptor_zero_burn_phase"
name = "Burn Phase"
trigger = { type = "effect_applied", effect_ids = [3287793170121044] }
duration_secs = 33.5
color = [133, 56, 85, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_missile_barrage"
name = "Missile Barrage"
trigger = { type = "ability_cast", ability_ids = [3286483205095424] }
duration_secs = 15.0
color = [35, 28, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_heavy_slash"
name = "Heavy Slash"
trigger = { type = "ability_cast", ability_ids = [3286530449735680] }
duration_secs = 20.0
color = [219, 30, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_chest_laser"
name = "Chest Laser"
trigger = { type = "ability_cast", ability_ids = [3285409463271424] }
duration_secs = 15.0
color = [224, 59, 212, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_beam_melee_mode"
name = "Beam (Melee Mode)"
trigger = { type = "effect_applied", effect_ids = [3284760923209993] }
duration_secs = 60.0
color = [219, 96, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_gravity_ranged_mode"
name = "Gravity (Ranged Mode)"
trigger = { type = "effect_applied", effect_ids = [3284760923209990] }
duration_secs = 60.0
color = [219, 96, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_concussion_mine"
name = "Concussion Mine"
trigger = { type = "ability_cast", ability_ids = [3321882325549056] }
duration_secs = 21.5
color = [24, 224, 221, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_gravity_delay"
name = "Gravity Delay"
trigger = { type = "ability_cast", ability_ids = [3321882325549056] }
duration_secs = 11.5
color = [204, 191, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_gravity_field"
name = "Gravity Field"
trigger = { type = "ability_cast", ability_ids = [3285972103987200] }
duration_secs = 33.0
color = [204, 191, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "corruptor_zero_beams_x_4"
name = "Beams x 4"
trigger = { type = "timer_expires", timer_id = "0e645f60-5ede-4a6c-8b95-344e1386dcec" }
duration_secs = 20.0
color = [133, 56, 85, 255]
difficulties = ["veteran", "master"]
