# Dread Master Brontes - The Dread Fortress
# Auto-converted from Orbs timers

[[boss]]
id = "dread_master_brontes"
name = "Dread Master Brontes"
area_name = "The Dread Fortress"
difficulties = ["master", "veteran"]
npc_names = ["Dread Master Brontes"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "dread_master_brontes_clone"
name = "Clone"
trigger = { type = "ability_cast", ability_ids = [3309152042483712] }
duration_secs = 30.0
color = [32, 168, 18, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_overcharge_1st"
name = "Overcharge 1st"
trigger = { type = "ability_cast", ability_ids = [3313824966901760] }
duration_secs = 30.0
color = [36, 32, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_fingers_knockback_1st"
name = "Fingers Knockback 1st"
trigger = { type = "ability_cast", ability_ids = [3303572879966208] }
duration_secs = 12.0
color = [224, 38, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_energy_sphere_p3"
name = "Energy Sphere P3"
trigger = { type = "ability_cast", ability_ids = [3313167836905472] }
duration_secs = 12.0
color = [219, 31, 28, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_overcharge"
name = "Overcharge"
trigger = { type = "ability_cast", ability_ids = [3313528614158336] }
duration_secs = 16.0
color = [36, 28, 219, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_fingers_knockback"
name = "Fingers Knockback"
trigger = { type = "timer_expires", timer_id = "dread_master_brontes_fingers_knockback_1st" }
duration_secs = 30.0
color = [219, 33, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "dread_master_brontes_fingers_knockback_2"
name = "Fingers Knockback_"
trigger = { type = "timer_expires", timer_id = "dread_master_brontes_fingers_knockback" }
duration_secs = 30.0
color = [224, 34, 29, 255]
difficulties = ["veteran", "master"]
