# Grob'thok, Who Feeds the Forge - The Dread Fortress
# Auto-converted from Orbs timers

[[boss]]
id = "grob_thok_who_feeds_the_forge"
name = "Grob'thok, Who Feeds the Forge"
area_name = "The Dread Fortress"
difficulties = ["master", "veteran"]
npc_names = ["Grob'thok, Who Feeds the Forge"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_pipe_smash_1st"
name = "Pipe Smash 1st"
trigger = { type = "combat_start" }
duration_secs = 60.0
color = [204, 182, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_pipe_smash"
name = "Pipe Smash"
trigger = { type = "ability_cast", ability_ids = [3307601559289856] }
duration_secs = 63.0
color = [204, 182, 30, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [3315585903493120] }
duration_secs = 25.0
color = [25, 148, 13, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_lava_dot"
name = "Lava DOT"
trigger = { type = "ability_cast", ability_ids = [3294703772499968] }
duration_secs = 30.0
color = [224, 108, 29, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_overhead_smash"
name = "Overhead Smash"
trigger = { type = "ability_cast", ability_ids = [3285993578823680] }
duration_secs = 33.0
color = [144, 24, 224, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_roar"
name = "Roar"
trigger = { type = "ability_cast", ability_ids = [3285997873790976] }
duration_secs = 15.0
color = [219, 28, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "grob_thok_who_feeds_the_forge_stunned"
name = "Stunned"
trigger = { type = "effect_applied", effect_ids = [3286745198100740] }
duration_secs = 10.0
color = [33, 224, 221, 255]
difficulties = ["veteran", "master"]
