# Nefra, Who Bars the Way - The Dread Fortress
# Auto-converted from Orbs timers

[[boss]]
id = "nefra_who_bars_the_way"
name = "Nefra, Who Bars the Way"
area_name = "The Dread Fortress"
difficulties = ["master", "veteran"]
npc_names = ["Nefra, Who Bars the Way"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "nefra_who_bars_the_way_voice_of_the_masters_1st"
name = "Voice of the Masters 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [29, 153, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_voice_of_the_masters"
name = "Voice of the Masters"
trigger = { type = "ability_cast", ability_ids = [3270007710547968] }
duration_secs = 30.0
color = [29, 153, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_dps_add_1st"
name = "DPS Add 1st"
trigger = { type = "combat_start" }
duration_secs = 30.0
color = [37, 219, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_tank_add_1st"
name = "TANK Add 1st"
trigger = { type = "combat_start" }
duration_secs = 45.0
color = [52, 28, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "nefra_who_bars_the_way_dps_add_vm"
name = "DPS Add VM"
trigger = { type = "ability_cast", ability_ids = [3308460552749056] }
duration_secs = 30.0
color = [32, 211, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "nefra_who_bars_the_way_tank_add_vm"
name = "TANK Add VM"
trigger = { type = "ability_cast", ability_ids = [3308164200005632] }
duration_secs = 30.0
color = [46, 32, 219, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "nefra_who_bars_the_way_tank_add"
name = "TANK Add"
trigger = { type = "ability_cast", ability_ids = [3308460552749056] }
duration_secs = 10.0
color = [33, 29, 224, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_dps_add"
name = "DPS Add"
trigger = { type = "ability_cast", ability_ids = [3308164200005632] }
duration_secs = 10.0
color = [32, 219, 213, 255]
difficulties = ["master"]

[[boss.timer]]
id = "nefra_who_bars_the_way_rng_add"
name = "RNG Add"
trigger = { type = "ability_cast", ability_ids = [3342034312101888] }
duration_secs = 30.0
color = [33, 149, 224, 255]
difficulties = ["master"]
