# Commander Rasha - Objective Meridian
# Auto-converted from Orbs timers

[[boss]]
id = "commander_rasha"
name = "Commander Rasha"
area_name = "Objective Meridian"
difficulties = ["master", "veteran"]
npc_names = ["Commander Rasha"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "commander_rasha_adds"
name = "Adds"
trigger = { type = "ability_cast", ability_ids = [4282928502669312] }
duration_secs = 45.0
color = [12, 136, 21, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_adds_2"
name = "Adds_"
trigger = { type = "ability_cast", ability_ids = [4284040899198976] }
duration_secs = 45.0
color = [22, 136, 20, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_shield"
name = "Shield"
trigger = { type = "ability_cast", ability_ids = [4283924935081984] }
duration_secs = 28.0
color = [38, 203, 213, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_artillery"
name = "Artillery"
trigger = { type = "ability_cast", ability_ids = [4282919912734720] }
duration_secs = 23.0
color = [220, 35, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_sweeping_gunfire"
name = "Sweeping Gunfire"
trigger = { type = "ability_cast", ability_ids = [4282954272473088] }
duration_secs = 15.0
color = [213, 113, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "commander_rasha_piercing_rounds"
name = "Piercing Rounds"
trigger = { type = "ability_cast", ability_ids = [4282958567440384] }
duration_secs = 20.0
color = [220, 37, 32, 255]
difficulties = ["veteran", "master"]
