# R10-X6 - Objective Meridian
# Auto-converted from Orbs timers

[[boss]]
id = "r10_x6"
name = "R10-X6"
area_name = "Objective Meridian"
difficulties = ["master", "veteran"]
npc_names = ["R10-X6"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "r10_x6_mines"
name = "Mines"
trigger = { type = "ability_cast", ability_ids = [4267475210338304] }
duration_secs = 30.0
color = [17, 113, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r10_x6_explosive_shot"
name = "Explosive Shot"
trigger = { type = "ability_cast", ability_ids = [4270069370585088] }
duration_secs = 18.0
color = [220, 40, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "r10_x6_explosive_shot_2"
name = "Explosive Shot_"
trigger = { type = "ability_cast", ability_ids = [4361857116667904] }
duration_secs = 16.0
color = [220, 26, 26, 255]
difficulties = ["veteran", "master"]
