# Colonel Vorgath - Explosive Conflict
# Auto-converted from Orbs timers

[[boss]]
id = "colonel_vorgath"
name = "Colonel Vorgath"
area_name = "Explosive Conflict"
difficulties = ["master", "veteran"]
npc_names = ["Colonel Vorgath"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "colonel_vorgath_threat_drop"
name = "Threat Drop"
trigger = { type = "ability_cast", ability_ids = [2919121767366656] }
duration_secs = 20.0
color = [39, 209, 208, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "colonel_vorgath_knocback"
name = "Knocback"
trigger = { type = "ability_cast", ability_ids = [2853275623751680] }
duration_secs = 15.0
color = [224, 108, 24, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "colonel_vorgath_grenade"
name = "Grenade"
trigger = { type = "ability_cast", ability_ids = [2853344343228416] }
duration_secs = 15.0
color = [214, 37, 32, 255]
difficulties = ["veteran", "master"]
