# Darth Serevin - The Battle of Ilum
# Auto-converted from Orbs timers

[[boss]]
id = "darth_serevin"
name = "Darth Serevin"
area_name = "The Battle of Ilum"
difficulties = ["master", "veteran"]
npc_names = ["Darth Serevin"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "darth_serevin_dark_blast_1st"
name = "Dark Blast 1st"
trigger = { type = "combat_start" }
duration_secs = 5.0
color = [140, 32, 220, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_serevin_affliction_1st"
name = "Affliction 1st"
trigger = { type = "combat_start" }
duration_secs = 10.0
color = [159, 19, 123, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_serevin_electro_storm_1st"
name = "Electro Storm 1st"
trigger = { type = "combat_start" }
duration_secs = 15.0
color = [101, 63, 236, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "darth_serevin_affliction"
name = "Affliction"
trigger = { type = "ability_cast", ability_ids = [2074314585145344] }
duration_secs = 15.0
color = [167, 20, 129, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "darth_serevin_affliction_mm"
name = "Affliction MM"
trigger = { type = "ability_cast", ability_ids = [2520995478896640] }
duration_secs = 20.0
color = [182, 5, 141, 255]
difficulties = ["master"]

[[boss.timer]]
id = "darth_serevin_electro_storm"
name = "Electro Storm"
trigger = { type = "ability_cast", ability_ids = [2074318880112640] }
duration_secs = 45.0
color = [101, 63, 236, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "darth_serevin_electro_storm_mm"
name = "Electro Storm MM"
trigger = { type = "ability_cast", ability_ids = [2520986888962048] }
duration_secs = 45.0
color = [101, 63, 236, 255]
difficulties = ["master"]

[[boss.timer]]
id = "darth_serevin_force_explosion"
name = "Force Explosion"
trigger = { type = "ability_cast", ability_ids = [2138734799618048] }
duration_secs = 20.0
color = [220, 36, 32, 255]
difficulties = ["veteran", "master"]
