# Krel Thak - The Battle of Ilum
# Auto-converted from Orbs timers

[[boss]]
id = "krel_thak"
name = "Krel Thak"
area_name = "The Battle of Ilum"
difficulties = ["master", "veteran"]
npc_names = ["Krel Thak"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "krel_thak_dirty_kick"
name = "Dirty Kick"
trigger = { type = "ability_cast", ability_ids = [2068301630930944] }
duration_secs = 30.0
color = [190, 170, 22, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_thermal_grenade"
name = "Thermal Grenade"
trigger = { type = "ability_cast", ability_ids = [2068318810800128] }
duration_secs = 15.0
color = [151, 105, 59, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_dirty_kick_mm"
name = "Dirty Kick MM"
trigger = { type = "ability_cast", ability_ids = [2522425703006208] }
duration_secs = 30.0
color = [205, 187, 36, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_thermal_grenade_mm"
name = "Thermal Grenade MM"
trigger = { type = "ability_cast", ability_ids = [2522464357711872] }
duration_secs = 15.0
color = [151, 109, 27, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_shielded_mm"
name = "Shielded MM"
trigger = { type = "effect_applied", effect_ids = [2522455767777537] }
duration_secs = 15.0
color = [43, 197, 205, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_shielded"
name = "Shielded"
trigger = { type = "effect_applied", effect_ids = [2068215731585282] }
duration_secs = 15.0
color = [36, 205, 191, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_shield_probe"
name = "Shield Probe"
trigger = { type = "timer_expires", timer_id = "krel_thak_shielded_mm" }
duration_secs = 15.0
color = [23, 197, 168, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "krel_thak_in_cover"
name = "In Cover"
trigger = { type = "effect_applied", effect_ids = [2068211436617728] }
duration_secs = 10.0
color = [21, 79, 182, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "krel_thak_in_cover_mm"
name = "In Cover MM"
trigger = { type = "effect_applied", effect_ids = [2522447177842688] }
duration_secs = 10.0
color = [19, 85, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "krel_thak_defense_screen"
name = "Defense Screen"
trigger = { type = "timer_expires", timer_id = "krel_thak_in_cover" }
duration_secs = 20.0
color = [5, 76, 174, 255]
difficulties = ["veteran", "master"]
