# Gil - Mandalorian Raiders
# Auto-converted from Orbs timers

[[boss]]
id = "gil"
name = "Gil"
area_name = "Mandalorian Raiders"
difficulties = ["master"]
npc_names = ["Gil"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "gil_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 210.0
color = [220, 31, 26, 255]
difficulties = ["master"]

[[boss.timer]]
id = "gil_jump_ww"
name = "Jump + WW"
trigger = { type = "ability_cast", ability_ids = [3250963825557504] }
duration_secs = 20.0
color = [189, 72, 220, 255]
difficulties = ["master"]

[[boss.timer]]
id = "gil_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [3250972415492096] }
duration_secs = 12.0
color = [40, 228, 224, 255]
difficulties = ["master"]
