# Mavrix Varad - Mandalorian Raiders
# Auto-converted from Orbs timers

[[boss]]
id = "mavrix_varad"
name = "Mavrix Varad"
area_name = "Mandalorian Raiders"
difficulties = ["master", "veteran"]
npc_names = ["Mavrix Varad"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "mavrix_varad_random_missile_vm"
name = "Random Missile VM"
trigger = { type = "ability_cast", ability_ids = [2455797875343360] }
duration_secs = 10.0
color = [220, 124, 32, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "mavrix_varad_random_missile_mm"
name = "Random Missile MM"
trigger = { type = "ability_cast", ability_ids = [2455797875343360] }
duration_secs = 18.0
color = [220, 120, 32, 255]
difficulties = ["master"]
