# Technician Canni & Elli-Vaa - Crisis on Umbara
# Auto-converted from Orbs timers

[[boss]]
id = "technician_canni_elli_vaa"
name = "Technician Canni & Elli-Vaa"
area_name = "Crisis on Umbara"
difficulties = ["master", "veteran"]
npc_names = ["Technician Canni & Elli-Vaa"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "technician_canni_elli_vaa_stealth"
name = "Stealth"
trigger = { type = "ability_cast", ability_ids = [4122318200635392] }
duration_secs = 15.0
color = [34, 220, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "technician_canni_elli_vaa_phase_2_end"
name = "Phase 2 end"
trigger = { type = "timer_expires", timer_id = "6871bf82-9b61-4c88-a251-c529f1e3c03b" }
duration_secs = 30.0
color = [220, 42, 32, 255]
phases = ["p3"]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "technician_canni_elli_vaa_knockback"
name = "Knockback"
trigger = { type = "ability_cast", ability_ids = [4122305315733504] }
duration_secs = 13.5
color = [220, 41, 32, 255]
difficulties = ["veteran", "master"]
