# The Vigilant - Czerka Core Meltdown
# Auto-converted from Orbs timers

[[boss]]
id = "the_vigilant"
name = "The Vigilant"
area_name = "Czerka Core Meltdown"
difficulties = ["master", "veteran"]
npc_names = ["The Vigilant"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "the_vigilant_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 480.0
color = [220, 42, 39, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_grapple"
name = "Grapple"
trigger = { type = "ability_cast", ability_ids = [3286667888689152] }
duration_secs = 12.0
color = [34, 222, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_beam"
name = "Beam"
trigger = { type = "ability_cast", ability_ids = [3264020526137344] }
duration_secs = 10.0
color = [194, 220, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_backhand"
name = "Backhand"
trigger = { type = "ability_cast", ability_ids = [3263689813655552] }
duration_secs = 10.0
color = [228, 127, 34, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "the_vigilant_slash"
name = "Slash"
trigger = { type = "ability_cast", ability_ids = [3263951806660608] }
duration_secs = 12.0
color = [213, 38, 163, 255]
difficulties = ["veteran", "master"]
