# Apex Ranphyx - Ruins of Nul
# Auto-converted from Orbs timers

[[boss]]
id = "apex_ranphyx"
name = "Apex Ranphyx"
area_name = "Ruins of Nul"
difficulties = ["master", "veteran"]
npc_names = ["Apex Ranphyx"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "apex_ranphyx_harrowing"
name = "Harrowing"
trigger = { type = "ability_cast", ability_ids = [4474780396814336] }
duration_secs = 20.0
color = [220, 43, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "apex_ranphyx_roar"
name = "Roar"
trigger = { type = "ability_cast", ability_ids = [4484667411529728] }
duration_secs = 21.0
color = [220, 30, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "apex_ranphyx_feral_pounce"
name = "Feral Pounce"
trigger = { type = "ability_cast", ability_ids = [4473539151265792] }
duration_secs = 32.0
color = [220, 126, 39, 255]
difficulties = ["veteran", "master"]
