# Bulwark - Directive 7
# Auto-converted from Orbs timers

[[boss]]
id = "bulwark"
name = "Bulwark"
area_name = "Directive 7"
difficulties = ["master", "veteran"]
npc_names = ["Bulwark"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "bulwark_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 330.0
color = [213, 32, 31, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bulwark_missile"
name = "Missile_"
trigger = { type = "ability_cast", ability_ids = [2970463806423040] }
duration_secs = 15.0
color = [213, 31, 178, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bulwark_smash"
name = "Smash_"
trigger = { type = "timer_expires", timer_id = "bulwark_missile" }
duration_secs = 5.0
color = [228, 124, 27, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bulwark_smash_2"
name = "Smash"
trigger = { type = "ability_cast", ability_ids = [2520419953278976] }
duration_secs = 30.0
color = [220, 132, 32, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "bulwark_missile_2"
name = "Missile"
trigger = { type = "ability_cast", ability_ids = [2520462902951936] }
duration_secs = 20.0
color = [220, 39, 182, 255]
difficulties = ["veteran", "master"]
