# Kephess the Undying - Terror From Beyond
# Auto-converted from Orbs timers

[[boss]]
id = "kephess_the_undying"
name = "Kephess the Undying"
area_name = "Terror From Beyond"
difficulties = ["master", "veteran"]
npc_names = ["Kephess the Undying"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "kephess_the_undying_invulnerable"
name = "Invulnerable"
trigger = { type = "ability_cast", ability_ids = [3008070540066816] }
duration_secs = 9.0
color = [20, 154, 174, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_laser_blast"
name = "Laser Blast"
trigger = { type = "ability_cast", ability_ids = [3012687629910016] }
duration_secs = 4.5
color = [46, 34, 228, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_corrupted_nanites"
name = "Corrupted Nanites"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [49, 190, 28, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_corrupted_nanites_2"
name = "Corrupted Nanites_"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [39, 197, 29, 255]
difficulties = ["master"]

[[boss.timer]]
id = "kephess_the_undying_nanites_jump"
name = "Nanites + Jump_"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [220, 45, 32, 255]
difficulties = ["veteran"]

[[boss.timer]]
id = "kephess_the_undying_nanites_jump_2"
name = "Nanites + Jump"
trigger = { type = "ability_cast", ability_ids = [2977765250826240] }
duration_secs = 15.0
color = [220, 36, 26, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "kephess_the_undying_1st_nanites_jump"
name = "1st Nanites + Jump"
trigger = { type = "ability_cast", ability_ids = [3008070540066816] }
duration_secs = 15.0
color = [222, 31, 30, 255]
difficulties = ["veteran", "master"]
