# HXI-54 Juggernaut - Boarding Party
# Auto-converted from Orbs timers

[[boss]]
id = "hxi_54_juggernaut"
name = "HXI-54 Juggernaut"
area_name = "Boarding Party"
difficulties = ["master", "veteran"]
npc_names = ["HXI-54 Juggernaut"]

[[boss.phase]]
id = "p1"
name = "Phase 1"
trigger = { type = "combat_start" }

[[boss.timer]]
id = "hxi_54_juggernaut_enrage"
name = "Enrage"
trigger = { type = "combat_start" }
duration_secs = 100.0
color = [205, 30, 37, 255]
difficulties = ["veteran", "master"]

[[boss.timer]]
id = "hxi_54_juggernaut_generator_drain"
name = "Generator Drain"
trigger = { type = "ability_cast", ability_ids = [2304219889532928] }
duration_secs = 33.0
color = [26, 217, 220, 255]
difficulties = ["veteran", "master"]
